import type {
  ArchitectureRelation,
  Asset,
  AssetSoftwareInstallation,
  ClusterEntity,
  ConnectivityObservation,
  NasAsset,
  NetworkPolicy,
  ProjectGroup,
  ResourcePoint,
  SoftwareInstall,
  SoftwareProduct,
  SoftwareRelease,
  SopDocument,
  TopologyGroup,
  VmAsset,
} from "@/domain/models";

// ==========================================
// 1. PROJECT GROUPS
// ==========================================
export const projectGroups: ProjectGroup[] = [
  {
    id: "rpa",
    name: "RPA Platform",
    code: "RPA",
    description: "Enterprise Robotic Process Automation platform (A360, Portal, APM, Common)",
    owner: "Automation COE",
    status: "ACTIVE",
  },
  {
    id: "mes",
    name: "MES Production",
    code: "MES",
    description: "Manufacturing Execution System and shop-floor automation",
    owner: "Smart Factory Team",
    status: "ACTIVE",
  },
  {
    id: "ai",
    name: "AI Platform",
    code: "AI_PLATFORM",
    description: "Enterprise GPU cluster, LLM serving, and model registry",
    owner: "AI Core Team",
    status: "ACTIVE",
  },
  {
    id: "data",
    name: "Data Platform",
    code: "DATA_PLATFORM",
    description: "Lakehouse analytics, ingestion pipelines, and event streaming",
    owner: "Enterprise Data Team",
    status: "ACTIVE",
  },
];

// ==========================================
// 2. TOPOLOGY GROUPS (RPA & Multi-Project)
// ==========================================
export const topologyGroups: TopologyGroup[] = [
  // A360 System & Environments
  {
    id: "tg-a360",
    projectGroupId: "rpa",
    name: "A360 Platform",
    groupType: "SYSTEM",
    system: "A360",
    description: "Automation Anywhere A360 enterprise RPA infrastructure",
  },
  {
    id: "tg-a360-prod",
    projectGroupId: "rpa",
    parentGroupId: "tg-a360",
    name: "PROD",
    groupType: "ENVIRONMENT",
    environment: "PROD",
    system: "A360",
    description: "Production tier for A360 domains",
  },
  {
    id: "tg-a360-prod-mem",
    projectGroupId: "rpa",
    parentGroupId: "tg-a360-prod",
    name: "MEMORY PROD",
    groupType: "DOMAIN",
    domain: "MEMORY",
    environment: "PROD",
    system: "A360",
    description: "Memory Business RPA Domain (PROD)",
  },
  {
    id: "tg-a360-prod-fnd",
    projectGroupId: "rpa",
    parentGroupId: "tg-a360-prod",
    name: "FOUNDRY PROD",
    groupType: "DOMAIN",
    domain: "FOUNDRY",
    environment: "PROD",
    system: "A360",
    description: "Foundry Business RPA Domain (PROD)",
  },
  {
    id: "tg-a360-prod-com",
    projectGroupId: "rpa",
    parentGroupId: "tg-a360-prod",
    name: "COMMON PROD",
    groupType: "DOMAIN",
    domain: "COMMON",
    environment: "PROD",
    system: "A360",
    description: "Corporate Common RPA Domain (PROD)",
  },
  {
    id: "tg-a360-qa",
    projectGroupId: "rpa",
    parentGroupId: "tg-a360",
    name: "QA",
    groupType: "ENVIRONMENT",
    environment: "QA",
    system: "A360",
    description: "Quality Assurance staging tier",
  },
  {
    id: "tg-a360-qa-mem",
    projectGroupId: "rpa",
    parentGroupId: "tg-a360-qa",
    name: "MEMORY QA",
    groupType: "DOMAIN",
    domain: "MEMORY",
    environment: "QA",
    system: "A360",
    description: "Memory Business RPA Domain (QA)",
  },
  {
    id: "tg-a360-qa-fnd",
    projectGroupId: "rpa",
    parentGroupId: "tg-a360-qa",
    name: "FOUNDRY QA",
    groupType: "DOMAIN",
    domain: "FOUNDRY",
    environment: "QA",
    system: "A360",
    description: "Foundry Business RPA Domain (QA)",
  },
  {
    id: "tg-a360-qa-com",
    projectGroupId: "rpa",
    parentGroupId: "tg-a360-qa",
    name: "COMMON QA",
    groupType: "DOMAIN",
    domain: "COMMON",
    environment: "QA",
    system: "A360",
    description: "Corporate Common RPA Domain (QA)",
  },
  {
    id: "tg-a360-dev",
    projectGroupId: "rpa",
    parentGroupId: "tg-a360",
    name: "DEV",
    groupType: "ENVIRONMENT",
    environment: "DEV",
    domain: "DEV",
    system: "A360",
    description: "Single-node development environment",
  },

  // RPA Portal System
  {
    id: "tg-portal",
    projectGroupId: "rpa",
    name: "RPA Portal",
    groupType: "SYSTEM",
    system: "RPA Portal",
    environment: "PROD",
    description: "Kubernetes-hosted RPA Operations Portal and Orchestration API",
  },
  {
    id: "tg-portal-fe",
    projectGroupId: "rpa",
    parentGroupId: "tg-portal",
    name: "Portal Frontend",
    groupType: "RUNTIME",
    system: "RPA Portal",
    environment: "PROD",
  },
  {
    id: "tg-portal-be",
    projectGroupId: "rpa",
    parentGroupId: "tg-portal",
    name: "Portal Backend",
    groupType: "RUNTIME",
    system: "RPA Portal",
    environment: "PROD",
  },
  {
    id: "tg-portal-mon",
    projectGroupId: "rpa",
    parentGroupId: "tg-portal",
    name: "Portal Monitor",
    groupType: "RUNTIME",
    system: "RPA Portal",
    environment: "PROD",
  },

  // APM Monitoring System
  {
    id: "tg-apm",
    projectGroupId: "rpa",
    name: "APM Monitoring",
    groupType: "SYSTEM",
    system: "APM",
    environment: "PROD",
    description: "Application Performance Monitoring probes and collector fleet",
  },

  // Common Function System
  {
    id: "tg-common-func",
    projectGroupId: "rpa",
    name: "Common Function",
    groupType: "SYSTEM",
    system: "Common Function",
    environment: "PROD",
    description: "Shared enterprise auth, license, and scheduling helpers",
  },

  // Placeholder Projects Topology Groups
  {
    id: "tg-mes-core",
    projectGroupId: "mes",
    name: "MES Core",
    groupType: "SYSTEM",
    system: "MES",
    environment: "PROD",
  },
  {
    id: "tg-ai-infer",
    projectGroupId: "ai",
    name: "AI Inference Fleet",
    groupType: "SYSTEM",
    system: "AI Platform",
    environment: "PROD",
  },
  {
    id: "tg-data-lake",
    projectGroupId: "data",
    name: "Lakehouse Storage",
    groupType: "SYSTEM",
    system: "Data Platform",
    environment: "PROD",
  },
];

// ==========================================
// 3. ASSETS (Compute, K8s, Storage, DBaaS)
// ==========================================
export const vms: Asset[] = [
  // ----------------------------------------
  // A. A360 PROD - MEMORY DOMAIN (AP x3, DB x2, NAS x1)
  // ----------------------------------------
  {
    id: "rpa-p-mem-ap01",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-P-MEM-AP01",
    ipAddress: "10.20.10.11",
    environment: "PROD",
    domain: "MEMORY",
    system: "A360",
    role: "AP",
    service: "A360 Memory",
    zone: "APP",
    criticality: "CRITICAL",
    health: "healthy",
    owner: "RPA Platform",
    osName: "Windows Server",
    osVersion: "2022",
    cpuCores: 8,
    memoryGb: 32,
    diskGb: 500,
    cpuPct: 42,
    memoryPct: 68,
    diskPct: 54,
    eoslDate: "2031-10-14",
    grafanaPath: "/d/vm-detail?var-host=RPA-P-MEM-AP01",
    lastVerifiedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    id: "rpa-p-mem-ap02",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-P-MEM-AP02",
    ipAddress: "10.20.10.12",
    environment: "PROD",
    domain: "MEMORY",
    system: "A360",
    role: "AP",
    service: "A360 Memory",
    zone: "APP",
    criticality: "CRITICAL",
    // Demo Scenario: Memory Warning (91%)
    health: "warning",
    owner: "RPA Platform",
    osName: "Windows Server",
    osVersion: "2022",
    cpuCores: 8,
    memoryGb: 32,
    diskGb: 500,
    cpuPct: 58,
    memoryPct: 91,
    diskPct: 62,
    description: "High memory utilization alert (91%)",
    eoslDate: "2031-10-14",
    grafanaPath: "/d/vm-detail?var-host=RPA-P-MEM-AP02",
    lastVerifiedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    id: "rpa-p-mem-ap03",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-P-MEM-AP03",
    ipAddress: "10.20.10.13",
    environment: "PROD",
    domain: "MEMORY",
    system: "A360",
    role: "AP",
    service: "A360 Memory",
    zone: "APP",
    criticality: "CRITICAL",
    health: "healthy",
    owner: "RPA Platform",
    osName: "Windows Server",
    osVersion: "2022",
    cpuCores: 8,
    memoryGb: 32,
    diskGb: 500,
    cpuPct: 37,
    memoryPct: 64,
    diskPct: 51,
    eoslDate: "2031-10-14",
    grafanaPath: "/d/vm-detail?var-host=RPA-P-MEM-AP03",
    lastVerifiedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    id: "rpa-p-mem-db01",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-P-MEM-DB01",
    ipAddress: "10.20.10.21",
    environment: "PROD",
    domain: "MEMORY",
    system: "A360",
    role: "DB",
    service: "MSSQL Memory",
    zone: "DB",
    criticality: "CRITICAL",
    health: "healthy",
    owner: "DBA Team",
    osName: "Windows Server",
    osVersion: "2019",
    cpuCores: 16,
    memoryGb: 64,
    diskGb: 2000,
    cpuPct: 35,
    memoryPct: 78,
    diskPct: 65,
    eoslDate: "2029-01-09",
    grafanaPath: "/d/vm-detail?var-host=RPA-P-MEM-DB01",
    lastVerifiedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    id: "rpa-p-mem-db02",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-P-MEM-DB02",
    ipAddress: "10.20.10.22",
    environment: "PROD",
    domain: "MEMORY",
    system: "A360",
    role: "DB",
    service: "MSSQL Memory",
    zone: "DB",
    criticality: "CRITICAL",
    health: "healthy",
    owner: "DBA Team",
    osName: "Windows Server",
    osVersion: "2019",
    cpuCores: 16,
    memoryGb: 64,
    diskGb: 2000,
    cpuPct: 18,
    memoryPct: 52,
    diskPct: 65,
    eoslDate: "2029-01-09",
    grafanaPath: "/d/vm-detail?var-host=RPA-P-MEM-DB02",
    lastVerifiedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    id: "rpa-p-mem-nas01",
    projectGroupId: "rpa",
    assetType: "NAS",
    hostname: "RPA-P-MEM-NAS01",
    ipAddress: "10.20.10.31",
    environment: "PROD",
    domain: "MEMORY",
    system: "A360",
    role: "Storage",
    service: "NAS Storage",
    zone: "SUPPORT",
    criticality: "HIGH",
    health: "healthy",
    owner: "Infra Storage Team",
    osName: "Storage OS",
    cpuCores: 4,
    memoryGb: 16,
    diskGb: 20480,
    lastVerifiedAt: "2026-09-23T18:00:00+09:00",
  },

  // ----------------------------------------
  // B. A360 PROD - FOUNDRY DOMAIN (AP x3, DB x2, NAS x1)
  // ----------------------------------------
  {
    id: "rpa-p-fnd-ap01",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-P-FND-AP01",
    ipAddress: "10.20.20.11",
    environment: "PROD",
    domain: "FOUNDRY",
    system: "A360",
    role: "AP",
    service: "A360 Foundry",
    zone: "APP",
    criticality: "CRITICAL",
    health: "healthy",
    owner: "RPA Platform",
    osName: "Windows Server",
    osVersion: "2022",
    cpuCores: 8,
    memoryGb: 32,
    diskGb: 500,
    cpuPct: 44,
    memoryPct: 71,
    diskPct: 58,
    eoslDate: "2031-10-14",
    grafanaPath: "/d/vm-detail?var-host=RPA-P-FND-AP01",
    lastVerifiedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    id: "rpa-p-fnd-ap02",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-P-FND-AP02",
    ipAddress: "10.20.20.12",
    environment: "PROD",
    domain: "FOUNDRY",
    system: "A360",
    role: "AP",
    service: "A360 Foundry",
    zone: "APP",
    criticality: "CRITICAL",
    health: "healthy",
    owner: "RPA Platform",
    osName: "Windows Server",
    osVersion: "2022",
    cpuCores: 8,
    memoryGb: 32,
    diskGb: 500,
    cpuPct: 39,
    memoryPct: 69,
    diskPct: 54,
    eoslDate: "2031-10-14",
    grafanaPath: "/d/vm-detail?var-host=RPA-P-FND-AP02",
    lastVerifiedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    id: "rpa-p-fnd-ap03",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-P-FND-AP03",
    ipAddress: "10.20.20.13",
    environment: "PROD",
    domain: "FOUNDRY",
    system: "A360",
    role: "AP",
    service: "A360 Foundry",
    zone: "APP",
    criticality: "CRITICAL",
    health: "healthy",
    owner: "RPA Platform",
    osName: "Windows Server",
    osVersion: "2022",
    cpuCores: 8,
    memoryGb: 32,
    diskGb: 500,
    cpuPct: 41,
    memoryPct: 65,
    diskPct: 52,
    eoslDate: "2031-10-14",
    grafanaPath: "/d/vm-detail?var-host=RPA-P-FND-AP03",
    lastVerifiedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    id: "rpa-p-fnd-db01",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-P-FND-DB01",
    ipAddress: "10.20.20.21",
    environment: "PROD",
    domain: "FOUNDRY",
    system: "A360",
    role: "DB",
    service: "MSSQL Foundry",
    zone: "DB",
    criticality: "CRITICAL",
    health: "healthy",
    owner: "DBA Team",
    osName: "Windows Server",
    osVersion: "2019",
    cpuCores: 16,
    memoryGb: 64,
    diskGb: 2500,
    cpuPct: 32,
    memoryPct: 74,
    diskPct: 68,
    eoslDate: "2029-01-09",
    grafanaPath: "/d/vm-detail?var-host=RPA-P-FND-DB01",
    lastVerifiedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    id: "rpa-p-fnd-db02",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-P-FND-DB02",
    ipAddress: "10.20.20.22",
    environment: "PROD",
    domain: "FOUNDRY",
    system: "A360",
    role: "DB",
    service: "MSSQL Foundry",
    zone: "DB",
    criticality: "CRITICAL",
    // Demo Scenario: Foundry DB Cluster Member Disk Warning (89%)
    health: "warning",
    owner: "DBA Team",
    osName: "Windows Server",
    osVersion: "2019",
    cpuCores: 16,
    memoryGb: 64,
    diskGb: 2500,
    cpuPct: 22,
    memoryPct: 61,
    diskPct: 89,
    description: "Database volume nearing capacity (89%)",
    eoslDate: "2029-01-09",
    grafanaPath: "/d/vm-detail?var-host=RPA-P-FND-DB02",
    lastVerifiedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    id: "rpa-p-fnd-nas01",
    projectGroupId: "rpa",
    assetType: "NAS",
    hostname: "RPA-P-FND-NAS01",
    ipAddress: "10.20.20.31",
    environment: "PROD",
    domain: "FOUNDRY",
    system: "A360",
    role: "Storage",
    service: "NAS Storage",
    zone: "SUPPORT",
    criticality: "HIGH",
    health: "healthy",
    owner: "Infra Storage Team",
    osName: "Storage OS",
    cpuCores: 4,
    memoryGb: 16,
    diskGb: 30720,
    lastVerifiedAt: "2026-09-23T18:00:00+09:00",
  },

  // ----------------------------------------
  // C. A360 PROD - COMMON DOMAIN (AP x3, DB x2, NAS x1)
  // ----------------------------------------
  {
    id: "rpa-p-com-ap01",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-P-COM-AP01",
    ipAddress: "10.20.30.11",
    environment: "PROD",
    domain: "COMMON",
    system: "A360",
    role: "AP",
    service: "A360 Common",
    zone: "APP",
    criticality: "CRITICAL",
    health: "healthy",
    owner: "RPA Platform",
    osName: "Windows Server",
    osVersion: "2022",
    cpuCores: 8,
    memoryGb: 32,
    diskGb: 500,
    cpuPct: 36,
    memoryPct: 62,
    diskPct: 48,
    eoslDate: "2031-10-14",
    grafanaPath: "/d/vm-detail?var-host=RPA-P-COM-AP01",
    lastVerifiedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    id: "rpa-p-com-ap02",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-P-COM-AP02",
    ipAddress: "10.20.30.12",
    environment: "PROD",
    domain: "COMMON",
    system: "A360",
    role: "AP",
    service: "A360 Common",
    zone: "APP",
    criticality: "CRITICAL",
    health: "healthy",
    owner: "RPA Platform",
    osName: "Windows Server",
    osVersion: "2022",
    cpuCores: 8,
    memoryGb: 32,
    diskGb: 500,
    cpuPct: 40,
    memoryPct: 66,
    diskPct: 53,
    eoslDate: "2031-10-14",
    grafanaPath: "/d/vm-detail?var-host=RPA-P-COM-AP02",
    lastVerifiedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    id: "rpa-p-com-ap03",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-P-COM-AP03",
    ipAddress: "10.20.30.13",
    environment: "PROD",
    domain: "COMMON",
    system: "A360",
    role: "AP",
    service: "A360 Common",
    zone: "APP",
    criticality: "CRITICAL",
    health: "healthy",
    owner: "RPA Platform",
    osName: "Windows Server",
    osVersion: "2022",
    cpuCores: 8,
    memoryGb: 32,
    diskGb: 500,
    cpuPct: 31,
    memoryPct: 59,
    diskPct: 49,
    eoslDate: "2031-10-14",
    grafanaPath: "/d/vm-detail?var-host=RPA-P-COM-AP03",
    lastVerifiedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    id: "rpa-p-com-db01",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-P-COM-DB01",
    ipAddress: "10.20.30.21",
    environment: "PROD",
    domain: "COMMON",
    system: "A360",
    role: "DB",
    service: "MSSQL Common",
    zone: "DB",
    criticality: "CRITICAL",
    health: "healthy",
    owner: "DBA Team",
    osName: "Windows Server",
    osVersion: "2019",
    cpuCores: 16,
    memoryGb: 64,
    diskGb: 2000,
    cpuPct: 29,
    memoryPct: 70,
    diskPct: 61,
    eoslDate: "2029-01-09",
    grafanaPath: "/d/vm-detail?var-host=RPA-P-COM-DB01",
    lastVerifiedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    id: "rpa-p-com-db02",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-P-COM-DB02",
    ipAddress: "10.20.30.22",
    environment: "PROD",
    domain: "COMMON",
    system: "A360",
    role: "DB",
    service: "MSSQL Common",
    zone: "DB",
    criticality: "CRITICAL",
    health: "healthy",
    owner: "DBA Team",
    osName: "Windows Server",
    osVersion: "2019",
    cpuCores: 16,
    memoryGb: 64,
    diskGb: 2000,
    cpuPct: 15,
    memoryPct: 48,
    diskPct: 59,
    eoslDate: "2029-01-09",
    grafanaPath: "/d/vm-detail?var-host=RPA-P-COM-DB02",
    lastVerifiedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    id: "rpa-p-com-nas01",
    projectGroupId: "rpa",
    assetType: "NAS",
    hostname: "RPA-P-COM-NAS01",
    ipAddress: "10.20.30.31",
    environment: "PROD",
    domain: "COMMON",
    system: "A360",
    role: "Storage",
    service: "NAS Storage",
    zone: "SUPPORT",
    criticality: "HIGH",
    health: "healthy",
    owner: "Infra Storage Team",
    osName: "Storage OS",
    cpuCores: 4,
    memoryGb: 16,
    diskGb: 25600,
    lastVerifiedAt: "2026-09-23T18:00:00+09:00",
  },

  // ----------------------------------------
  // D. A360 QA DOMAINS (Memory, Foundry, Common)
  // ----------------------------------------
  // QA Memory
  {
    id: "rpa-q-mem-ap01",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-Q-MEM-AP01",
    ipAddress: "10.30.10.11",
    environment: "QA",
    domain: "MEMORY",
    system: "A360",
    role: "AP",
    service: "A360 Memory QA",
    zone: "APP",
    criticality: "MEDIUM",
    health: "healthy",
    owner: "QA Team",
    osName: "Windows Server",
    osVersion: "2022",
    cpuCores: 4,
    memoryGb: 16,
    diskGb: 300,
    cpuPct: 25,
    memoryPct: 45,
    diskPct: 40,
    eoslDate: "2031-10-14",
  },
  {
    id: "rpa-q-mem-ap02",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-Q-MEM-AP02",
    ipAddress: "10.30.10.12",
    environment: "QA",
    domain: "MEMORY",
    system: "A360",
    role: "AP",
    service: "A360 Memory QA",
    zone: "APP",
    criticality: "MEDIUM",
    health: "healthy",
    owner: "QA Team",
    osName: "Windows Server",
    osVersion: "2022",
    cpuCores: 4,
    memoryGb: 16,
    diskGb: 300,
    cpuPct: 22,
    memoryPct: 43,
    diskPct: 39,
  },
  {
    id: "rpa-q-mem-ap03",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-Q-MEM-AP03",
    ipAddress: "10.30.10.13",
    environment: "QA",
    domain: "MEMORY",
    system: "A360",
    role: "AP",
    service: "A360 Memory QA",
    zone: "APP",
    criticality: "MEDIUM",
    health: "healthy",
    owner: "QA Team",
    osName: "Windows Server",
    osVersion: "2022",
    cpuCores: 4,
    memoryGb: 16,
    diskGb: 300,
    cpuPct: 28,
    memoryPct: 47,
    diskPct: 41,
  },
  {
    id: "rpa-q-mem-db01",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-Q-MEM-DB01",
    ipAddress: "10.30.10.21",
    environment: "QA",
    domain: "MEMORY",
    system: "A360",
    role: "DB",
    service: "MSSQL Memory QA",
    zone: "DB",
    criticality: "HIGH",
    health: "healthy",
    owner: "QA Team",
    osName: "Windows Server",
    osVersion: "2019",
    cpuCores: 8,
    memoryGb: 32,
    diskGb: 1000,
    cpuPct: 20,
    memoryPct: 55,
    diskPct: 48,
  },
  {
    id: "rpa-q-mem-db02",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-Q-MEM-DB02",
    ipAddress: "10.30.10.22",
    environment: "QA",
    domain: "MEMORY",
    system: "A360",
    role: "DB",
    service: "MSSQL Memory QA",
    zone: "DB",
    criticality: "HIGH",
    health: "healthy",
    owner: "QA Team",
    osName: "Windows Server",
    osVersion: "2019",
    cpuCores: 8,
    memoryGb: 32,
    diskGb: 1000,
    cpuPct: 10,
    memoryPct: 35,
    diskPct: 46,
  },
  {
    id: "rpa-q-mem-nas01",
    projectGroupId: "rpa",
    assetType: "NAS",
    hostname: "RPA-Q-MEM-NAS01",
    ipAddress: "10.30.10.31",
    environment: "QA",
    domain: "MEMORY",
    system: "A360",
    role: "Storage",
    service: "NAS QA",
    zone: "SUPPORT",
    criticality: "MEDIUM",
    health: "healthy",
    owner: "QA Team",
    capacityTb: 10,
    usedCapacityTb: 4.2,
    protocol: "NFS",
    status: "ONLINE",
  },

  // QA Foundry
  {
    id: "rpa-q-fnd-ap01",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-Q-FND-AP01",
    ipAddress: "10.30.20.11",
    environment: "QA",
    domain: "FOUNDRY",
    system: "A360",
    role: "AP",
    service: "A360 Foundry QA",
    zone: "APP",
    criticality: "MEDIUM",
    health: "healthy",
    owner: "QA Team",
    osName: "Windows Server",
    osVersion: "2022",
    cpuCores: 4,
    memoryGb: 16,
    diskGb: 300,
  },
  {
    id: "rpa-q-fnd-ap02",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-Q-FND-AP02",
    ipAddress: "10.30.20.12",
    environment: "QA",
    domain: "FOUNDRY",
    system: "A360",
    role: "AP",
    service: "A360 Foundry QA",
    zone: "APP",
    criticality: "MEDIUM",
    health: "healthy",
    owner: "QA Team",
    osName: "Windows Server",
    osVersion: "2022",
    cpuCores: 4,
    memoryGb: 16,
    diskGb: 300,
  },
  {
    id: "rpa-q-fnd-ap03",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-Q-FND-AP03",
    ipAddress: "10.30.20.13",
    environment: "QA",
    domain: "FOUNDRY",
    system: "A360",
    role: "AP",
    service: "A360 Foundry QA",
    zone: "APP",
    criticality: "MEDIUM",
    health: "healthy",
    owner: "QA Team",
    osName: "Windows Server",
    osVersion: "2022",
    cpuCores: 4,
    memoryGb: 16,
    diskGb: 300,
  },
  {
    id: "rpa-q-fnd-db01",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-Q-FND-DB01",
    ipAddress: "10.30.20.21",
    environment: "QA",
    domain: "FOUNDRY",
    system: "A360",
    role: "DB",
    service: "MSSQL Foundry QA",
    zone: "DB",
    criticality: "HIGH",
    health: "healthy",
    owner: "QA Team",
    osName: "Windows Server",
    osVersion: "2019",
    cpuCores: 8,
    memoryGb: 32,
    diskGb: 1000,
  },
  {
    id: "rpa-q-fnd-db02",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-Q-FND-DB02",
    ipAddress: "10.30.20.22",
    environment: "QA",
    domain: "FOUNDRY",
    system: "A360",
    role: "DB",
    service: "MSSQL Foundry QA",
    zone: "DB",
    criticality: "HIGH",
    health: "healthy",
    owner: "QA Team",
    osName: "Windows Server",
    osVersion: "2019",
    cpuCores: 8,
    memoryGb: 32,
    diskGb: 1000,
  },
  {
    id: "rpa-q-fnd-nas01",
    projectGroupId: "rpa",
    assetType: "NAS",
    hostname: "RPA-Q-FND-NAS01",
    ipAddress: "10.30.20.31",
    environment: "QA",
    domain: "FOUNDRY",
    system: "A360",
    role: "Storage",
    service: "NAS QA",
    zone: "SUPPORT",
    criticality: "MEDIUM",
    health: "healthy",
    owner: "QA Team",
    capacityTb: 10,
    usedCapacityTb: 3.8,
    protocol: "NFS",
    status: "ONLINE",
  },

  // QA Common
  {
    id: "rpa-q-com-ap01",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-Q-COM-AP01",
    ipAddress: "10.30.30.11",
    environment: "QA",
    domain: "COMMON",
    system: "A360",
    role: "AP",
    service: "A360 Common QA",
    zone: "APP",
    criticality: "MEDIUM",
    health: "healthy",
    owner: "QA Team",
    osName: "Windows Server",
    osVersion: "2022",
    cpuCores: 4,
    memoryGb: 16,
    diskGb: 300,
  },
  {
    id: "rpa-q-com-ap02",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-Q-COM-AP02",
    ipAddress: "10.30.30.12",
    environment: "QA",
    domain: "COMMON",
    system: "A360",
    role: "AP",
    service: "A360 Common QA",
    zone: "APP",
    criticality: "MEDIUM",
    health: "healthy",
    owner: "QA Team",
    osName: "Windows Server",
    osVersion: "2022",
    cpuCores: 4,
    memoryGb: 16,
    diskGb: 300,
  },
  {
    id: "rpa-q-com-ap03",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-Q-COM-AP03",
    ipAddress: "10.30.30.13",
    environment: "QA",
    domain: "COMMON",
    system: "A360",
    role: "AP",
    service: "A360 Common QA",
    zone: "APP",
    criticality: "MEDIUM",
    health: "healthy",
    owner: "QA Team",
    osName: "Windows Server",
    osVersion: "2022",
    cpuCores: 4,
    memoryGb: 16,
    diskGb: 300,
  },
  {
    id: "rpa-q-com-db01",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-Q-COM-DB01",
    ipAddress: "10.30.30.21",
    environment: "QA",
    domain: "COMMON",
    system: "A360",
    role: "DB",
    service: "MSSQL Common QA",
    zone: "DB",
    criticality: "HIGH",
    health: "healthy",
    owner: "QA Team",
    osName: "Windows Server",
    osVersion: "2019",
    cpuCores: 8,
    memoryGb: 32,
    diskGb: 1000,
  },
  {
    id: "rpa-q-com-db02",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-Q-COM-DB02",
    ipAddress: "10.30.30.22",
    environment: "QA",
    domain: "COMMON",
    system: "A360",
    role: "DB",
    service: "MSSQL Common QA",
    zone: "DB",
    criticality: "HIGH",
    health: "healthy",
    owner: "QA Team",
    osName: "Windows Server",
    osVersion: "2019",
    cpuCores: 8,
    memoryGb: 32,
    diskGb: 1000,
  },
  {
    id: "rpa-q-com-nas01",
    projectGroupId: "rpa",
    assetType: "NAS",
    hostname: "RPA-Q-COM-NAS01",
    ipAddress: "10.30.30.31",
    environment: "QA",
    domain: "COMMON",
    system: "A360",
    role: "Storage",
    service: "NAS QA",
    zone: "SUPPORT",
    criticality: "MEDIUM",
    health: "healthy",
    owner: "QA Team",
    capacityTb: 10,
    usedCapacityTb: 3.5,
    protocol: "NFS",
    status: "ONLINE",
  },

  // ----------------------------------------
  // E. A360 DEV (Single AP, Standalone DB, NAS)
  // ----------------------------------------
  {
    id: "rpa-d-ap01",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-D-AP01",
    ipAddress: "10.40.10.11",
    environment: "DEV",
    domain: "DEV",
    system: "A360",
    role: "AP",
    service: "A360 Dev",
    zone: "APP",
    criticality: "LOW",
    health: "healthy",
    owner: "Dev Team",
    osName: "Windows Server",
    osVersion: "2022",
    cpuCores: 4,
    memoryGb: 16,
    diskGb: 200,
    cpuPct: 15,
    memoryPct: 35,
    diskPct: 28,
  },
  {
    id: "rpa-d-db01",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-D-DB01",
    ipAddress: "10.40.10.21",
    environment: "DEV",
    domain: "DEV",
    system: "A360",
    role: "DB",
    service: "MSSQL Dev Standalone",
    zone: "DB",
    criticality: "LOW",
    health: "healthy",
    owner: "Dev Team",
    osName: "Windows Server",
    osVersion: "2019",
    cpuCores: 4,
    memoryGb: 16,
    diskGb: 500,
    cpuPct: 10,
    memoryPct: 30,
    diskPct: 22,
  },
  {
    id: "rpa-d-nas01",
    projectGroupId: "rpa",
    assetType: "NAS",
    hostname: "RPA-D-NAS01",
    ipAddress: "10.40.10.31",
    environment: "DEV",
    domain: "DEV",
    system: "A360",
    role: "Storage",
    service: "NAS Dev",
    zone: "SUPPORT",
    criticality: "LOW",
    health: "healthy",
    owner: "Dev Team",
    capacityTb: 5,
    usedCapacityTb: 1.1,
    protocol: "NFS",
    status: "ONLINE",
  },

  // ----------------------------------------
  // F. RPA PORTAL (Kubernetes Runtime: FE x2, BE x2, MON x2, DBaaS x1)
  // ----------------------------------------
  {
    id: "portal-fe-01",
    projectGroupId: "rpa",
    assetType: "K8S_WORKLOAD",
    hostname: "PORTAL-FE-01",
    ipAddress: "10.50.10.11",
    environment: "PROD",
    domain: "PORTAL",
    system: "RPA Portal",
    role: "Frontend",
    service: "Portal Web",
    zone: "WEB",
    criticality: "HIGH",
    health: "healthy",
    owner: "Portal DevOps",
    cpuCores: 2,
    memoryGb: 4,
    diskGb: 50,
    cpuPct: 28,
    memoryPct: 52,
    diskPct: 30,
  },
  {
    id: "portal-fe-02",
    projectGroupId: "rpa",
    assetType: "K8S_WORKLOAD",
    hostname: "PORTAL-FE-02",
    ipAddress: "10.50.10.12",
    environment: "PROD",
    domain: "PORTAL",
    system: "RPA Portal",
    role: "Frontend",
    service: "Portal Web",
    zone: "WEB",
    criticality: "HIGH",
    health: "healthy",
    owner: "Portal DevOps",
    cpuCores: 2,
    memoryGb: 4,
    diskGb: 50,
    cpuPct: 31,
    memoryPct: 54,
    diskPct: 32,
  },
  {
    id: "portal-be-01",
    projectGroupId: "rpa",
    assetType: "K8S_WORKLOAD",
    hostname: "PORTAL-BE-01",
    ipAddress: "10.50.10.21",
    environment: "PROD",
    domain: "PORTAL",
    system: "RPA Portal",
    role: "Backend",
    service: "Portal API",
    zone: "APP",
    criticality: "CRITICAL",
    health: "healthy",
    owner: "Portal DevOps",
    cpuCores: 4,
    memoryGb: 8,
    diskGb: 100,
    cpuPct: 45,
    memoryPct: 62,
    diskPct: 40,
  },
  {
    id: "portal-be-02",
    projectGroupId: "rpa",
    assetType: "K8S_WORKLOAD",
    hostname: "PORTAL-BE-02",
    ipAddress: "10.50.10.22",
    environment: "PROD",
    domain: "PORTAL",
    system: "RPA Portal",
    role: "Backend",
    service: "Portal API",
    zone: "APP",
    criticality: "CRITICAL",
    health: "healthy",
    owner: "Portal DevOps",
    cpuCores: 4,
    memoryGb: 8,
    diskGb: 100,
    cpuPct: 42,
    memoryPct: 60,
    diskPct: 38,
  },
  {
    id: "portal-mon-01",
    projectGroupId: "rpa",
    assetType: "K8S_WORKLOAD",
    hostname: "PORTAL-MON-01",
    ipAddress: "10.50.10.31",
    environment: "PROD",
    domain: "PORTAL",
    system: "RPA Portal",
    role: "Monitor",
    service: "Portal Monitor",
    zone: "CONTROL",
    criticality: "MEDIUM",
    health: "healthy",
    owner: "Portal DevOps",
    cpuCores: 2,
    memoryGb: 4,
    diskGb: 80,
    cpuPct: 19,
    memoryPct: 48,
    diskPct: 35,
  },
  {
    id: "portal-mon-02",
    projectGroupId: "rpa",
    assetType: "K8S_WORKLOAD",
    hostname: "PORTAL-MON-02",
    ipAddress: "10.50.10.32",
    environment: "PROD",
    domain: "PORTAL",
    system: "RPA Portal",
    role: "Monitor",
    service: "Portal Monitor",
    zone: "CONTROL",
    criticality: "MEDIUM",
    health: "healthy",
    owner: "Portal DevOps",
    cpuCores: 2,
    memoryGb: 4,
    diskGb: 80,
    cpuPct: 18,
    memoryPct: 46,
    diskPct: 34,
  },
  {
    id: "portal-dbaas",
    projectGroupId: "rpa",
    assetType: "DBAAS",
    hostname: "RPA-PORTAL-DB",
    ipAddress: "10.50.20.10",
    environment: "PROD",
    domain: "PORTAL",
    system: "RPA Portal",
    role: "DBaaS",
    service: "Managed PostgreSQL DBaaS",
    zone: "DB",
    criticality: "CRITICAL",
    health: "healthy",
    owner: "DBA Team",
    cpuCores: 8,
    memoryGb: 32,
    diskGb: 1000,
    cpuPct: 30,
    memoryPct: 58,
    diskPct: 44,
  },

  // ----------------------------------------
  // G. APM SERVERS (Monitoring x2)
  // ----------------------------------------
  {
    id: "rpa-apm01",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-APM01",
    ipAddress: "10.10.50.11",
    environment: "PROD",
    domain: "APM",
    system: "APM",
    role: "APM",
    service: "APM Collector",
    zone: "CONTROL",
    criticality: "HIGH",
    health: "healthy",
    owner: "Observability Team",
    osName: "Linux RHEL",
    osVersion: "8.8",
    cpuCores: 8,
    memoryGb: 32,
    diskGb: 1000,
    cpuPct: 48,
    memoryPct: 67,
    diskPct: 58,
  },
  {
    id: "rpa-apm02",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-APM02",
    ipAddress: "10.10.50.12",
    environment: "PROD",
    domain: "APM",
    system: "APM",
    role: "APM",
    service: "APM Collector",
    zone: "CONTROL",
    criticality: "HIGH",
    health: "healthy",
    owner: "Observability Team",
    osName: "Linux RHEL",
    osVersion: "8.8",
    cpuCores: 8,
    memoryGb: 32,
    diskGb: 1000,
    cpuPct: 44,
    memoryPct: 64,
    diskPct: 56,
  },

  // ----------------------------------------
  // H. COMMON FUNCTION (Independent Common AP & DB)
  // ----------------------------------------
  {
    id: "rpa-common-ap01",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-COMMON-AP01",
    ipAddress: "10.10.60.11",
    environment: "PROD",
    domain: "COMMON_FUNCTION",
    system: "Common Function",
    role: "Common AP",
    service: "Common Function AP",
    zone: "APP",
    criticality: "HIGH",
    health: "healthy",
    owner: "RPA Core Team",
    osName: "Windows Server",
    osVersion: "2019",
    cpuCores: 8,
    memoryGb: 16,
    diskGb: 500,
    cpuPct: 34,
    memoryPct: 61,
    diskPct: 45,
  },
  {
    id: "rpa-common-db01",
    projectGroupId: "rpa",
    assetType: "VM",
    hostname: "RPA-COMMON-DB01",
    ipAddress: "10.10.60.21",
    environment: "PROD",
    domain: "COMMON_FUNCTION",
    system: "Common Function",
    role: "Common DB",
    service: "Common Function DB",
    zone: "DB",
    criticality: "HIGH",
    health: "healthy",
    owner: "DBA Team",
    osName: "Windows Server",
    osVersion: "2019",
    cpuCores: 8,
    memoryGb: 32,
    diskGb: 1000,
    cpuPct: 26,
    memoryPct: 54,
    diskPct: 50,
  },

  // ----------------------------------------
  // I. MULTI-PROJECT PLACEHOLDERS (MES, AI, Data)
  // ----------------------------------------
  {
    id: "mes-app01",
    projectGroupId: "mes",
    assetType: "VM",
    hostname: "MES-LINE-APP01",
    ipAddress: "10.70.10.11",
    environment: "PROD",
    domain: "FACTORY_A",
    system: "MES",
    role: "MES Core",
    service: "MES Line Dispatcher",
    zone: "APP",
    criticality: "CRITICAL",
    health: "healthy",
    owner: "Smart Factory Team",
    osName: "Linux RHEL",
    cpuCores: 16,
    memoryGb: 64,
  },
  {
    id: "mes-db01",
    projectGroupId: "mes",
    assetType: "VM",
    hostname: "MES-LINE-DB01",
    ipAddress: "10.70.10.21",
    environment: "PROD",
    domain: "FACTORY_A",
    system: "MES",
    role: "DB",
    service: "Oracle MES DB",
    zone: "DB",
    criticality: "CRITICAL",
    health: "healthy",
    owner: "Smart Factory Team",
    osName: "Linux RHEL",
    cpuCores: 32,
    memoryGb: 128,
  },
  {
    id: "ai-gpu01",
    projectGroupId: "ai",
    assetType: "PHYSICAL_SERVER",
    hostname: "AI-GPU-NODE01",
    ipAddress: "10.80.10.11",
    environment: "PROD",
    domain: "TRAINING",
    system: "AI Platform",
    role: "GPU Worker",
    service: "LLM Serving",
    zone: "APP",
    criticality: "HIGH",
    health: "healthy",
    owner: "AI Core Team",
    cpuCores: 64,
    memoryGb: 512,
  },
  {
    id: "data-lake01",
    projectGroupId: "data",
    assetType: "CONTAINER",
    hostname: "DATA-INGEST-01",
    ipAddress: "10.90.10.11",
    environment: "PROD",
    domain: "INGEST",
    system: "Data Platform",
    role: "Kafka Broker",
    service: "Event Streaming",
    zone: "APP",
    criticality: "HIGH",
    health: "healthy",
    owner: "Enterprise Data Team",
  },
];

// ==========================================
// 4. CLUSTERS (Logical Entities)
// ==========================================
export const clusters: ClusterEntity[] = [
  // PROD Clusters
  {
    id: "rpa-p-mem-mssql",
    projectGroupId: "rpa",
    name: "RPA-P-MEM-MSSQL",
    type: "MSCS",
    vip: "10.20.10.10",
    environment: "PROD",
    domain: "MEMORY",
    system: "A360",
    zone: "DB",
    status: "HEALTHY",
    owner: "DBA Team",
    description: "Active/Passive SQL Server Failover Cluster for Memory Domain",
    members: [
      {
        clusterId: "rpa-p-mem-mssql",
        assetId: "rpa-p-mem-db01",
        hostname: "RPA-P-MEM-DB01",
        ipAddress: "10.20.10.21",
        role: "ACTIVE",
        priority: 1,
        status: "ONLINE",
      },
      {
        clusterId: "rpa-p-mem-mssql",
        assetId: "rpa-p-mem-db02",
        hostname: "RPA-P-MEM-DB02",
        ipAddress: "10.20.10.22",
        role: "PASSIVE",
        priority: 2,
        status: "STANDBY",
      },
    ],
    services: [
      {
        clusterId: "rpa-p-mem-mssql",
        serviceType: "MSSQLSERVER",
        instanceName: "MSSQL-MEM-PRD",
        port: 1433,
        version: "2019 CU18",
      },
    ],
  },
  {
    id: "rpa-p-fnd-mssql",
    projectGroupId: "rpa",
    name: "RPA-P-FND-MSSQL",
    type: "MSCS",
    vip: "10.20.20.10",
    environment: "PROD",
    domain: "FOUNDRY",
    system: "A360",
    zone: "DB",
    status: "HEALTHY",
    owner: "DBA Team",
    description: "Active/Passive SQL Server Failover Cluster for Foundry Domain",
    members: [
      {
        clusterId: "rpa-p-fnd-mssql",
        assetId: "rpa-p-fnd-db01",
        hostname: "RPA-P-FND-DB01",
        ipAddress: "10.20.20.21",
        role: "ACTIVE",
        priority: 1,
        status: "ONLINE",
      },
      {
        clusterId: "rpa-p-fnd-mssql",
        assetId: "rpa-p-fnd-db02",
        hostname: "RPA-P-FND-DB02",
        ipAddress: "10.20.20.22",
        role: "PASSIVE",
        priority: 2,
        status: "STANDBY",
      },
    ],
    services: [
      {
        clusterId: "rpa-p-fnd-mssql",
        serviceType: "MSSQLSERVER",
        instanceName: "MSSQL-FND-PRD",
        port: 1433,
        version: "2019 CU18",
      },
    ],
  },
  {
    id: "rpa-p-com-mssql",
    projectGroupId: "rpa",
    name: "RPA-P-COM-MSSQL",
    type: "MSCS",
    vip: "10.20.30.10",
    environment: "PROD",
    domain: "COMMON",
    system: "A360",
    zone: "DB",
    status: "HEALTHY",
    owner: "DBA Team",
    description: "Active/Passive SQL Server Failover Cluster for Common Domain",
    members: [
      {
        clusterId: "rpa-p-com-mssql",
        assetId: "rpa-p-com-db01",
        hostname: "RPA-P-COM-DB01",
        ipAddress: "10.20.30.21",
        role: "ACTIVE",
        priority: 1,
        status: "ONLINE",
      },
      {
        clusterId: "rpa-p-com-mssql",
        assetId: "rpa-p-com-db02",
        hostname: "RPA-P-COM-DB02",
        ipAddress: "10.20.30.22",
        role: "PASSIVE",
        priority: 2,
        status: "STANDBY",
      },
    ],
    services: [
      {
        clusterId: "rpa-p-com-mssql",
        serviceType: "MSSQLSERVER",
        instanceName: "MSSQL-COM-PRD",
        port: 1433,
        version: "2019 CU18",
      },
    ],
  },

  // QA Clusters
  {
    id: "rpa-q-mem-mssql",
    projectGroupId: "rpa",
    name: "RPA-Q-MEM-MSSQL",
    type: "MSCS",
    vip: "10.30.10.10",
    environment: "QA",
    domain: "MEMORY",
    system: "A360",
    zone: "DB",
    status: "HEALTHY",
    members: [
      {
        clusterId: "rpa-q-mem-mssql",
        assetId: "rpa-q-mem-db01",
        hostname: "RPA-Q-MEM-DB01",
        ipAddress: "10.30.10.21",
        role: "ACTIVE",
        priority: 1,
        status: "ONLINE",
      },
      {
        clusterId: "rpa-q-mem-mssql",
        assetId: "rpa-q-mem-db02",
        hostname: "RPA-Q-MEM-DB02",
        ipAddress: "10.30.10.22",
        role: "PASSIVE",
        priority: 2,
        status: "STANDBY",
      },
    ],
    services: [
      {
        clusterId: "rpa-q-mem-mssql",
        serviceType: "MSSQLSERVER",
        instanceName: "MSSQL-MEM-QA",
        port: 1433,
      },
    ],
  },
  {
    id: "rpa-q-fnd-mssql",
    projectGroupId: "rpa",
    name: "RPA-Q-FND-MSSQL",
    type: "MSCS",
    vip: "10.30.20.10",
    environment: "QA",
    domain: "FOUNDRY",
    system: "A360",
    zone: "DB",
    status: "HEALTHY",
    members: [
      {
        clusterId: "rpa-q-fnd-mssql",
        assetId: "rpa-q-fnd-db01",
        hostname: "RPA-Q-FND-DB01",
        ipAddress: "10.30.20.21",
        role: "ACTIVE",
        priority: 1,
        status: "ONLINE",
      },
      {
        clusterId: "rpa-q-fnd-mssql",
        assetId: "rpa-q-fnd-db02",
        hostname: "RPA-Q-FND-DB02",
        ipAddress: "10.30.20.22",
        role: "PASSIVE",
        priority: 2,
        status: "STANDBY",
      },
    ],
    services: [
      {
        clusterId: "rpa-q-fnd-mssql",
        serviceType: "MSSQLSERVER",
        instanceName: "MSSQL-FND-QA",
        port: 1433,
      },
    ],
  },
  {
    id: "rpa-q-com-mssql",
    projectGroupId: "rpa",
    name: "RPA-Q-COM-MSSQL",
    type: "MSCS",
    vip: "10.30.30.10",
    environment: "QA",
    domain: "COMMON",
    system: "A360",
    zone: "DB",
    status: "HEALTHY",
    members: [
      {
        clusterId: "rpa-q-com-mssql",
        assetId: "rpa-q-com-db01",
        hostname: "RPA-Q-COM-DB01",
        ipAddress: "10.30.30.21",
        role: "ACTIVE",
        priority: 1,
        status: "ONLINE",
      },
      {
        clusterId: "rpa-q-com-mssql",
        assetId: "rpa-q-com-db02",
        hostname: "RPA-Q-COM-DB02",
        ipAddress: "10.30.30.22",
        role: "PASSIVE",
        priority: 2,
        status: "STANDBY",
      },
    ],
    services: [
      {
        clusterId: "rpa-q-com-mssql",
        serviceType: "MSSQLSERVER",
        instanceName: "MSSQL-COM-QA",
        port: 1433,
      },
    ],
  },
];

// ==========================================
// 5. NAS ASSETS (Storage Inventory)
// ==========================================
export const nasAssets: NasAsset[] = [
  {
    id: "rpa-p-mem-nas01",
    projectGroupId: "rpa",
    assetType: "NAS",
    hostname: "RPA-P-MEM-NAS01",
    ipAddress: "10.20.10.31",
    environment: "PROD",
    domain: "MEMORY",
    system: "A360",
    role: "Storage",
    service: "NAS Storage",
    zone: "SUPPORT",
    criticality: "HIGH",
    health: "healthy",
    vendor: "NetApp",
    capacityTb: 20,
    usedCapacityTb: 12.4,
    protocol: "NFS",
    mountPath: "/data/rpa/memory/bots",
    status: "ONLINE",
    targetVms: ["rpa-p-mem-ap01", "rpa-p-mem-ap02", "rpa-p-mem-ap03"],
  },
  {
    id: "rpa-p-fnd-nas01",
    projectGroupId: "rpa",
    assetType: "NAS",
    hostname: "RPA-P-FND-NAS01",
    ipAddress: "10.20.20.31",
    environment: "PROD",
    domain: "FOUNDRY",
    system: "A360",
    role: "Storage",
    service: "NAS Storage",
    zone: "SUPPORT",
    criticality: "HIGH",
    health: "healthy",
    vendor: "Dell EMC",
    capacityTb: 30,
    usedCapacityTb: 18.2,
    protocol: "NFS",
    mountPath: "/data/rpa/foundry/bots",
    status: "ONLINE",
    targetVms: ["rpa-p-fnd-ap01", "rpa-p-fnd-ap02", "rpa-p-fnd-ap03"],
  },
  {
    id: "rpa-p-com-nas01",
    projectGroupId: "rpa",
    assetType: "NAS",
    hostname: "RPA-P-COM-NAS01",
    ipAddress: "10.20.30.31",
    environment: "PROD",
    domain: "COMMON",
    system: "A360",
    role: "Storage",
    service: "NAS Storage",
    zone: "SUPPORT",
    criticality: "HIGH",
    health: "healthy",
    vendor: "NetApp",
    capacityTb: 25,
    usedCapacityTb: 14.1,
    protocol: "NFS",
    mountPath: "/data/rpa/common/shared",
    status: "ONLINE",
    targetVms: ["rpa-p-com-ap01", "rpa-p-com-ap02", "rpa-p-com-ap03"],
  },
  {
    id: "rpa-q-mem-nas01",
    projectGroupId: "rpa",
    assetType: "NAS",
    hostname: "RPA-Q-MEM-NAS01",
    ipAddress: "10.30.10.31",
    environment: "QA",
    domain: "MEMORY",
    system: "A360",
    role: "Storage",
    service: "NAS QA",
    zone: "SUPPORT",
    criticality: "MEDIUM",
    health: "healthy",
    vendor: "NetApp",
    capacityTb: 10,
    usedCapacityTb: 4.2,
    protocol: "NFS",
    mountPath: "/data/qa/memory",
    status: "ONLINE",
  },
  {
    id: "rpa-q-fnd-nas01",
    projectGroupId: "rpa",
    assetType: "NAS",
    hostname: "RPA-Q-FND-NAS01",
    ipAddress: "10.30.20.31",
    environment: "QA",
    domain: "FOUNDRY",
    system: "A360",
    role: "Storage",
    service: "NAS QA",
    zone: "SUPPORT",
    criticality: "MEDIUM",
    health: "healthy",
    vendor: "Dell EMC",
    capacityTb: 10,
    usedCapacityTb: 3.8,
    protocol: "NFS",
    mountPath: "/data/qa/foundry",
    status: "ONLINE",
  },
  {
    id: "rpa-q-com-nas01",
    projectGroupId: "rpa",
    assetType: "NAS",
    hostname: "RPA-Q-COM-NAS01",
    ipAddress: "10.30.30.31",
    environment: "QA",
    domain: "COMMON",
    system: "A360",
    role: "Storage",
    service: "NAS QA",
    zone: "SUPPORT",
    criticality: "MEDIUM",
    health: "healthy",
    vendor: "NetApp",
    capacityTb: 10,
    usedCapacityTb: 3.5,
    protocol: "NFS",
    mountPath: "/data/qa/common",
    status: "ONLINE",
  },
  {
    id: "rpa-d-nas01",
    projectGroupId: "rpa",
    assetType: "NAS",
    hostname: "RPA-D-NAS01",
    ipAddress: "10.40.10.31",
    environment: "DEV",
    domain: "DEV",
    system: "A360",
    role: "Storage",
    service: "NAS Dev",
    zone: "SUPPORT",
    criticality: "LOW",
    health: "healthy",
    vendor: "Synology",
    capacityTb: 5,
    usedCapacityTb: 1.1,
    protocol: "NFS",
    mountPath: "/data/dev",
    status: "ONLINE",
  },
];

// ==========================================
// 6. ARCHITECTURE RELATIONS
// ==========================================
export const relations: ArchitectureRelation[] = [
  // Portal Internal Relations
  {
    id: "rel-portal-fe-be",
    projectGroupId: "rpa",
    sourceEntityType: "TOPOLOGY_GROUP",
    sourceEntityId: "tg-portal-fe",
    targetEntityType: "TOPOLOGY_GROUP",
    targetEntityId: "tg-portal-be",
    relationType: "SERVICE",
    protocol: "HTTP",
    port: 8080,
    description: "Portal Frontend calls Backend API",
  },
  {
    id: "rel-portal-be-dbaas",
    projectGroupId: "rpa",
    sourceEntityType: "TOPOLOGY_GROUP",
    sourceEntityId: "tg-portal-be",
    targetEntityType: "ASSET",
    targetEntityId: "portal-dbaas",
    relationType: "DATABASE",
    protocol: "TCP",
    port: 5432,
    description: "Portal Backend connects to PostgreSQL DBaaS",
  },
  {
    id: "rel-portal-mon-be",
    projectGroupId: "rpa",
    sourceEntityType: "TOPOLOGY_GROUP",
    sourceEntityId: "tg-portal-mon",
    targetEntityType: "TOPOLOGY_GROUP",
    targetEntityId: "tg-portal-be",
    relationType: "MONITORING",
    protocol: "HTTP",
    port: 9090,
    description: "Portal Prometheus Monitor scrapes backend metrics",
  },

  // Portal Backend -> A360 Domains (Management/Service)
  {
    id: "rel-portal-mem",
    projectGroupId: "rpa",
    sourceEntityType: "TOPOLOGY_GROUP",
    sourceEntityId: "tg-portal-be",
    targetEntityType: "TOPOLOGY_GROUP",
    targetEntityId: "tg-a360-prod-mem",
    relationType: "MANAGEMENT",
    protocol: "HTTPS",
    port: 443,
    description: "Portal Bot Orchestration calls Memory A360 API",
  },
  {
    id: "rel-portal-fnd",
    projectGroupId: "rpa",
    sourceEntityType: "TOPOLOGY_GROUP",
    sourceEntityId: "tg-portal-be",
    targetEntityType: "TOPOLOGY_GROUP",
    targetEntityId: "tg-a360-prod-fnd",
    relationType: "MANAGEMENT",
    protocol: "HTTPS",
    port: 443,
    description: "Portal Bot Orchestration calls Foundry A360 API",
  },
  {
    id: "rel-portal-com",
    projectGroupId: "rpa",
    sourceEntityType: "TOPOLOGY_GROUP",
    sourceEntityId: "tg-portal-be",
    targetEntityType: "TOPOLOGY_GROUP",
    targetEntityId: "tg-a360-prod-com",
    relationType: "MANAGEMENT",
    protocol: "HTTPS",
    port: 443,
    description: "Portal Bot Orchestration calls Common A360 API",
  },

  // PROD Memory AP -> DB Cluster & NAS
  {
    id: "rel-mem-ap-db",
    projectGroupId: "rpa",
    sourceEntityType: "TOPOLOGY_GROUP",
    sourceEntityId: "tg-a360-prod-mem",
    targetEntityType: "CLUSTER",
    targetEntityId: "rpa-p-mem-mssql",
    relationType: "DATABASE",
    protocol: "TCP",
    port: 1433,
    description: "Memory AP pool queries MSSQL Cluster VIP",
  },
  {
    id: "rel-mem-ap-nas",
    projectGroupId: "rpa",
    sourceEntityType: "TOPOLOGY_GROUP",
    sourceEntityId: "tg-a360-prod-mem",
    targetEntityType: "NAS",
    targetEntityId: "rpa-p-mem-nas01",
    relationType: "STORAGE",
    protocol: "NFS",
    port: 2049,
    description: "Memory AP pool mounts NAS share",
  },

  // PROD Foundry AP -> DB Cluster & NAS
  {
    id: "rel-fnd-ap-db",
    projectGroupId: "rpa",
    sourceEntityType: "TOPOLOGY_GROUP",
    sourceEntityId: "tg-a360-prod-fnd",
    targetEntityType: "CLUSTER",
    targetEntityId: "rpa-p-fnd-mssql",
    relationType: "DATABASE",
    protocol: "TCP",
    port: 1433,
    description: "Foundry AP pool queries MSSQL Cluster VIP",
  },
  {
    id: "rel-fnd-ap-nas",
    projectGroupId: "rpa",
    sourceEntityType: "TOPOLOGY_GROUP",
    sourceEntityId: "tg-a360-prod-fnd",
    targetEntityType: "NAS",
    targetEntityId: "rpa-p-fnd-nas01",
    relationType: "STORAGE",
    protocol: "NFS",
    port: 2049,
    description: "Foundry AP pool mounts NAS share",
  },

  // PROD Common AP -> DB Cluster & NAS
  {
    id: "rel-com-ap-db",
    projectGroupId: "rpa",
    sourceEntityType: "TOPOLOGY_GROUP",
    sourceEntityId: "tg-a360-prod-com",
    targetEntityType: "CLUSTER",
    targetEntityId: "rpa-p-com-mssql",
    relationType: "DATABASE",
    protocol: "TCP",
    port: 1433,
    description: "Common AP pool queries MSSQL Cluster VIP",
  },
  {
    id: "rel-com-ap-nas",
    projectGroupId: "rpa",
    sourceEntityType: "TOPOLOGY_GROUP",
    sourceEntityId: "tg-a360-prod-com",
    targetEntityType: "NAS",
    targetEntityId: "rpa-p-com-nas01",
    relationType: "STORAGE",
    protocol: "NFS",
    port: 2049,
    description: "Common AP pool mounts NAS share",
  },

  // QA Relations
  {
    id: "rel-qa-mem-db",
    projectGroupId: "rpa",
    sourceEntityType: "TOPOLOGY_GROUP",
    sourceEntityId: "tg-a360-qa-mem",
    targetEntityType: "CLUSTER",
    targetEntityId: "rpa-q-mem-mssql",
    relationType: "DATABASE",
    protocol: "TCP",
    port: 1433,
  },
  {
    id: "rel-qa-fnd-db",
    projectGroupId: "rpa",
    sourceEntityType: "TOPOLOGY_GROUP",
    sourceEntityId: "tg-a360-qa-fnd",
    targetEntityType: "CLUSTER",
    targetEntityId: "rpa-q-fnd-mssql",
    relationType: "DATABASE",
    protocol: "TCP",
    port: 1433,
  },
  {
    id: "rel-qa-com-db",
    projectGroupId: "rpa",
    sourceEntityType: "TOPOLOGY_GROUP",
    sourceEntityId: "tg-a360-qa-com",
    targetEntityType: "CLUSTER",
    targetEntityId: "rpa-q-com-mssql",
    relationType: "DATABASE",
    protocol: "TCP",
    port: 1433,
  },

  // DEV Relation (Standalone AP -> DB)
  {
    id: "rel-dev-ap-db",
    projectGroupId: "rpa",
    sourceEntityType: "ASSET",
    sourceEntityId: "rpa-d-ap01",
    targetEntityType: "ASSET",
    targetEntityId: "rpa-d-db01",
    relationType: "DATABASE",
    protocol: "TCP",
    port: 1433,
    description: "DEV AP connects to standalone DEV DB",
  },
  {
    id: "rel-dev-ap-nas",
    projectGroupId: "rpa",
    sourceEntityType: "ASSET",
    sourceEntityId: "rpa-d-ap01",
    targetEntityType: "NAS",
    targetEntityId: "rpa-d-nas01",
    relationType: "STORAGE",
    protocol: "NFS",
    port: 2049,
  },

  // Common Function Relation (AP -> DB)
  {
    id: "rel-common-func-ap-db",
    projectGroupId: "rpa",
    sourceEntityType: "ASSET",
    sourceEntityId: "rpa-common-ap01",
    targetEntityType: "ASSET",
    targetEntityId: "rpa-common-db01",
    relationType: "DATABASE",
    protocol: "TCP",
    port: 1433,
    description: "Common Function AP connects to Common Function DB",
  },

  // APM Monitoring Relations
  {
    id: "rel-apm-mem-ap",
    projectGroupId: "rpa",
    sourceEntityType: "ASSET",
    sourceEntityId: "rpa-apm01",
    targetEntityType: "TOPOLOGY_GROUP",
    targetEntityId: "tg-a360-prod-mem",
    relationType: "MONITORING",
    protocol: "TCP",
    port: 10050,
    description: "APM Agent metric collection",
  },
  {
    id: "rel-apm-fnd-ap",
    projectGroupId: "rpa",
    sourceEntityType: "ASSET",
    sourceEntityId: "rpa-apm01",
    targetEntityType: "TOPOLOGY_GROUP",
    targetEntityId: "tg-a360-prod-fnd",
    relationType: "MONITORING",
    protocol: "TCP",
    port: 10050,
  },
  {
    id: "rel-apm-com-ap",
    projectGroupId: "rpa",
    sourceEntityType: "ASSET",
    sourceEntityId: "rpa-apm02",
    targetEntityType: "TOPOLOGY_GROUP",
    targetEntityId: "tg-a360-prod-com",
    relationType: "MONITORING",
    protocol: "TCP",
    port: 10050,
  },
];

// ==========================================
// 7. NETWORK POLICIES & TELEGRAF OBSERVATIONS
// ==========================================
export const policies: NetworkPolicy[] = [
  // Policy 1: Memory AP -> MSSQL Cluster VIP (1433)
  {
    id: "pol-p-mem-ap01-db",
    projectGroupId: "rpa",
    sourceVmId: "rpa-p-mem-ap01",
    sourceName: "RPA-P-MEM-AP01",
    sourceIp: "10.20.10.11",
    targetVmId: "rpa-p-mem-db01",
    targetName: "RPA-P-MEM-MSSQL",
    targetIp: "10.20.10.10",
    protocol: "TCP",
    port: 1433,
    direction: "ONE_WAY",
    approvalStatus: "APPROVED",
    approvedAt: "2026-01-15T09:00:00+09:00",
    expiresAt: "2027-01-15T09:00:00+09:00",
    requestId: "REQ-FW-2026-0112",
    purpose: "A360 Memory DB query",
    owner: "RPA Platform",
  },
  {
    id: "pol-p-mem-ap02-db",
    projectGroupId: "rpa",
    sourceVmId: "rpa-p-mem-ap02",
    sourceName: "RPA-P-MEM-AP02",
    sourceIp: "10.20.10.12",
    targetVmId: "rpa-p-mem-db01",
    targetName: "RPA-P-MEM-MSSQL",
    targetIp: "10.20.10.10",
    protocol: "TCP",
    port: 1433,
    direction: "ONE_WAY",
    approvalStatus: "APPROVED",
    approvedAt: "2026-01-15T09:00:00+09:00",
    expiresAt: "2027-01-15T09:00:00+09:00",
    requestId: "REQ-FW-2026-0113",
    purpose: "A360 Memory DB query",
    owner: "RPA Platform",
  },
  {
    id: "pol-p-mem-ap03-db",
    projectGroupId: "rpa",
    sourceVmId: "rpa-p-mem-ap03",
    sourceName: "RPA-P-MEM-AP03",
    sourceIp: "10.20.10.13",
    targetVmId: "rpa-p-mem-db01",
    targetName: "RPA-P-MEM-MSSQL",
    targetIp: "10.20.10.10",
    protocol: "TCP",
    port: 1433,
    direction: "ONE_WAY",
    approvalStatus: "APPROVED",
    approvedAt: "2026-01-15T09:00:00+09:00",
    expiresAt: "2027-01-15T09:00:00+09:00",
    requestId: "REQ-FW-2026-0114",
    purpose: "A360 Memory DB query",
    owner: "RPA Platform",
  },

  // Policy 2: Foundry AP -> MSSQL Cluster VIP (1433)
  {
    id: "pol-p-fnd-ap01-db",
    projectGroupId: "rpa",
    sourceVmId: "rpa-p-fnd-ap01",
    sourceName: "RPA-P-FND-AP01",
    sourceIp: "10.20.20.11",
    targetVmId: "rpa-p-fnd-db01",
    targetName: "RPA-P-FND-MSSQL",
    targetIp: "10.20.20.10",
    protocol: "TCP",
    port: 1433,
    direction: "ONE_WAY",
    approvalStatus: "APPROVED",
    approvedAt: "2026-02-10T10:00:00+09:00",
    expiresAt: "2027-02-10T10:00:00+09:00",
    requestId: "REQ-FW-2026-0245",
  },

  // Demo Scenario: Common AP Policy Expiring in D-7
  {
    id: "pol-p-com-ap01-db",
    projectGroupId: "rpa",
    sourceVmId: "rpa-p-com-ap01",
    sourceName: "RPA-P-COM-AP01",
    sourceIp: "10.20.30.11",
    targetVmId: "rpa-p-com-db01",
    targetName: "RPA-P-COM-MSSQL",
    targetIp: "10.20.30.10",
    protocol: "TCP",
    port: 1433,
    direction: "ONE_WAY",
    approvalStatus: "APPROVED",
    approvedAt: "2025-09-28T00:00:00+09:00",
    // 7 days from now (2026-09-21 + 7 = 2026-09-28)
    expiresAt: "2026-09-28T00:00:00+09:00",
    requestId: "REQ-FW-2025-0899",
    purpose: "Common Domain DB Sync",
    owner: "RPA Platform",
  },

  // Demo Scenario: QA Network Policy Expired but TCP UP
  {
    id: "pol-q-mem-ap01-db",
    projectGroupId: "rpa",
    sourceVmId: "rpa-q-mem-ap01",
    sourceName: "RPA-Q-MEM-AP01",
    sourceIp: "10.30.10.11",
    targetVmId: "rpa-q-mem-db01",
    targetName: "RPA-Q-MEM-MSSQL",
    targetIp: "10.30.10.10",
    protocol: "TCP",
    port: 1433,
    direction: "ONE_WAY",
    approvalStatus: "APPROVED",
    approvedAt: "2025-09-01T00:00:00+09:00",
    // Expired 10 days ago (2026-09-11)
    expiresAt: "2026-09-11T00:00:00+09:00",
    requestId: "REQ-FW-2025-0720",
    purpose: "QA Memory Test Query",
    owner: "QA Team",
  },

  // Demo Scenario: DEV AP -> DB TCP DOWN (Policy approved, reachability failed)
  {
    id: "pol-d-ap01-db",
    projectGroupId: "rpa",
    sourceVmId: "rpa-d-ap01",
    sourceName: "RPA-D-AP01",
    sourceIp: "10.40.10.11",
    targetVmId: "rpa-d-db01",
    targetName: "RPA-D-DB01",
    targetIp: "10.40.10.21",
    protocol: "TCP",
    port: 1433,
    direction: "ONE_WAY",
    approvalStatus: "APPROVED",
    approvedAt: "2026-03-01T00:00:00+09:00",
    expiresAt: "2027-03-01T00:00:00+09:00",
    requestId: "REQ-FW-2026-0381",
    purpose: "DEV DB Connection",
    owner: "Dev Team",
  },

  // Portal Backend -> DBaaS (Port 5432)
  {
    id: "pol-portal-be-dbaas",
    projectGroupId: "rpa",
    sourceVmId: "portal-be-01",
    sourceName: "PORTAL-BE-01",
    sourceIp: "10.50.10.21",
    targetVmId: "portal-dbaas",
    targetName: "RPA-PORTAL-DB",
    targetIp: "10.50.20.10",
    protocol: "TCP",
    port: 5432,
    direction: "ONE_WAY",
    approvalStatus: "APPROVED",
    expiresAt: "2027-06-30T00:00:00+09:00",
    requestId: "REQ-FW-2026-0511",
    purpose: "Portal backend data store",
  },

  // Portal Backend -> Memory A360 AP (Bidirectional HTTPS 443)
  {
    id: "pol-portal-be-mem-ap",
    projectGroupId: "rpa",
    sourceVmId: "portal-be-01",
    sourceName: "PORTAL-BE-01",
    sourceIp: "10.50.10.21",
    targetVmId: "rpa-p-mem-ap01",
    targetName: "RPA-P-MEM-AP01",
    targetIp: "10.20.10.11",
    protocol: "TCP",
    port: 443,
    direction: "BIDIRECTIONAL",
    approvalStatus: "APPROVED",
    expiresAt: "2027-06-30T00:00:00+09:00",
    requestId: "REQ-FW-2026-0520",
    purpose: "Orchestration API Callback",
  },

  // Common Function AP -> DB
  {
    id: "pol-common-ap-db",
    projectGroupId: "rpa",
    sourceVmId: "rpa-common-ap01",
    sourceName: "RPA-COMMON-AP01",
    sourceIp: "10.10.60.11",
    targetVmId: "rpa-common-db01",
    targetName: "RPA-COMMON-DB01",
    targetIp: "10.10.60.21",
    protocol: "TCP",
    port: 1433,
    direction: "ONE_WAY",
    approvalStatus: "APPROVED",
    expiresAt: "2027-05-01T00:00:00+09:00",
    requestId: "REQ-FW-2026-0410",
    purpose: "Common Function Database",
  },

  // APM -> Memory AP (Port 10050)
  {
    id: "pol-apm-mem-ap01",
    projectGroupId: "rpa",
    sourceVmId: "rpa-apm01",
    sourceName: "RPA-APM01",
    sourceIp: "10.10.50.11",
    targetVmId: "rpa-p-mem-ap01",
    targetName: "RPA-P-MEM-AP01",
    targetIp: "10.20.10.11",
    protocol: "TCP",
    port: 10050,
    direction: "ONE_WAY",
    approvalStatus: "APPROVED",
    expiresAt: "2027-09-01T00:00:00+09:00",
    requestId: "REQ-FW-2026-0701",
    purpose: "APM Telemetry Probe",
  },
];

export const observations: ConnectivityObservation[] = [
  // Normal TCP UP for pol-p-mem-ap01-db
  {
    sourceVmId: "rpa-p-mem-ap01",
    sourceName: "RPA-P-MEM-AP01",
    sourceIp: "10.20.10.11",
    targetVmId: "rpa-p-mem-db01",
    targetName: "RPA-P-MEM-MSSQL",
    targetIp: "10.20.10.10",
    protocol: "TCP",
    port: 1433,
    ping: "UP",
    tcp: "UP",
    pingLatencyMs: 1.2,
    tcpLatencyMs: 2.4,
    checkedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    sourceVmId: "rpa-p-mem-ap02",
    sourceName: "RPA-P-MEM-AP02",
    sourceIp: "10.20.10.12",
    targetVmId: "rpa-p-mem-db01",
    targetName: "RPA-P-MEM-MSSQL",
    targetIp: "10.20.10.10",
    protocol: "TCP",
    port: 1433,
    ping: "UP",
    tcp: "UP",
    pingLatencyMs: 1.1,
    tcpLatencyMs: 2.2,
    checkedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    sourceVmId: "rpa-p-mem-ap03",
    sourceName: "RPA-P-MEM-AP03",
    sourceIp: "10.20.10.13",
    targetVmId: "rpa-p-mem-db01",
    targetName: "RPA-P-MEM-MSSQL",
    targetIp: "10.20.10.10",
    protocol: "TCP",
    port: 1433,
    ping: "UP",
    tcp: "UP",
    pingLatencyMs: 1.3,
    tcpLatencyMs: 2.5,
    checkedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    sourceVmId: "rpa-p-fnd-ap01",
    sourceName: "RPA-P-FND-AP01",
    sourceIp: "10.20.20.11",
    targetVmId: "rpa-p-fnd-db01",
    targetName: "RPA-P-FND-MSSQL",
    targetIp: "10.20.20.10",
    protocol: "TCP",
    port: 1433,
    ping: "UP",
    tcp: "UP",
    pingLatencyMs: 1.0,
    tcpLatencyMs: 2.1,
    checkedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    sourceVmId: "rpa-p-com-ap01",
    sourceName: "RPA-P-COM-AP01",
    sourceIp: "10.20.30.11",
    targetVmId: "rpa-p-com-db01",
    targetName: "RPA-P-COM-MSSQL",
    targetIp: "10.20.30.10",
    protocol: "TCP",
    port: 1433,
    ping: "UP",
    tcp: "UP",
    pingLatencyMs: 1.4,
    tcpLatencyMs: 2.7,
    checkedAt: "2026-09-23T18:00:00+09:00",
  },

  // Demo Case: QA Policy Expired but TCP is UP!
  {
    sourceVmId: "rpa-q-mem-ap01",
    sourceName: "RPA-Q-MEM-AP01",
    sourceIp: "10.30.10.11",
    targetVmId: "rpa-q-mem-db01",
    targetName: "RPA-Q-MEM-MSSQL",
    targetIp: "10.30.10.10",
    protocol: "TCP",
    port: 1433,
    ping: "UP",
    tcp: "UP",
    pingLatencyMs: 1.5,
    tcpLatencyMs: 3.1,
    checkedAt: "2026-09-23T18:00:00+09:00",
  },

  // Demo Case: DEV AP -> DB TCP DOWN!
  {
    sourceVmId: "rpa-d-ap01",
    sourceName: "RPA-D-AP01",
    sourceIp: "10.40.10.11",
    targetVmId: "rpa-d-db01",
    targetName: "RPA-D-DB01",
    targetIp: "10.40.10.21",
    protocol: "TCP",
    port: 1433,
    ping: "UP",
    tcp: "DOWN",
    pingLatencyMs: 1.8,
    tcpLatencyMs: null,
    checkedAt: "2026-09-23T18:00:00+09:00",
  },

  // Portal Backend -> DBaaS
  {
    sourceVmId: "portal-be-01",
    sourceName: "PORTAL-BE-01",
    sourceIp: "10.50.10.21",
    targetVmId: "portal-dbaas",
    targetName: "RPA-PORTAL-DB",
    targetIp: "10.50.20.10",
    protocol: "TCP",
    port: 5432,
    ping: "UP",
    tcp: "UP",
    pingLatencyMs: 0.8,
    tcpLatencyMs: 1.6,
    checkedAt: "2026-09-23T18:00:00+09:00",
  },

  // Bidirectional Probe (Forward UP, Reverse UP)
  {
    sourceVmId: "portal-be-01",
    sourceName: "PORTAL-BE-01",
    sourceIp: "10.50.10.21",
    targetVmId: "rpa-p-mem-ap01",
    targetName: "RPA-P-MEM-AP01",
    targetIp: "10.20.10.11",
    protocol: "TCP",
    port: 443,
    ping: "UP",
    tcp: "UP",
    pingLatencyMs: 1.2,
    tcpLatencyMs: 2.3,
    checkedAt: "2026-09-23T18:00:00+09:00",
  },
  {
    sourceVmId: "rpa-p-mem-ap01",
    sourceName: "RPA-P-MEM-AP01",
    sourceIp: "10.20.10.11",
    targetVmId: "portal-be-01",
    targetName: "PORTAL-BE-01",
    targetIp: "10.50.10.21",
    protocol: "TCP",
    port: 443,
    ping: "UP",
    tcp: "UP",
    pingLatencyMs: 1.2,
    tcpLatencyMs: 2.3,
    checkedAt: "2026-09-23T18:00:00+09:00",
  },

  // Common Function AP -> DB
  {
    sourceVmId: "rpa-common-ap01",
    sourceName: "RPA-COMMON-AP01",
    sourceIp: "10.10.60.11",
    targetVmId: "rpa-common-db01",
    targetName: "RPA-COMMON-DB01",
    targetIp: "10.10.60.21",
    protocol: "TCP",
    port: 1433,
    ping: "UP",
    tcp: "UP",
    pingLatencyMs: 1.1,
    tcpLatencyMs: 2.0,
    checkedAt: "2026-09-23T18:00:00+09:00",
  },

  // APM -> AP01
  {
    sourceVmId: "rpa-apm01",
    sourceName: "RPA-APM01",
    sourceIp: "10.10.50.11",
    targetVmId: "rpa-p-mem-ap01",
    targetName: "RPA-P-MEM-AP01",
    targetIp: "10.20.10.11",
    protocol: "TCP",
    port: 10050,
    ping: "UP",
    tcp: "UP",
    pingLatencyMs: 1.2,
    tcpLatencyMs: 2.2,
    checkedAt: "2026-09-23T18:00:00+09:00",
  },
];

// ==========================================
// 8. 3-TIER SOFTWARE LIFECYCLE & CATALOG
// ==========================================
export const softwareProducts: SoftwareProduct[] = [
  {
    id: "sp-tomcat",
    name: "Apache Tomcat",
    vendor: "Apache Software Foundation",
    category: "Application Server",
    description: "Open source Java Servlet Container",
  },
  {
    id: "sp-java",
    name: "Oracle Java SE",
    vendor: "Oracle",
    category: "Runtime / JDK",
    description: "Enterprise Java Runtime Environment",
  },
  {
    id: "sp-mssql",
    name: "Microsoft SQL Server",
    vendor: "Microsoft",
    category: "Database",
    description: "Enterprise Relational Database Management System",
  },
  {
    id: "sp-a360",
    name: "Automation Anywhere A360",
    vendor: "Automation Anywhere",
    category: "RPA Platform",
    description: "Cloud-native RPA Bot Agent & Control Room engine",
  },
  {
    id: "sp-custom",
    name: "Custom RPA Engine Plugin",
    vendor: "Internal Engineering",
    category: "Proprietary",
    description: "Internal banking interface automation plugin",
  },
];

export const softwareReleases: SoftwareRelease[] = [
  {
    id: "sr-tomcat-9",
    productId: "sp-tomcat",
    productName: "Apache Tomcat",
    version: "9.0.73",
    vendor: "Apache Software Foundation",
    releaseDate: "2023-03-01",
    supportEndDate: "2026-11-15",
    // Demo Scenario: EOSL D90
    eoslDate: "2026-11-15",
    status: "D90",
    versionMatchRule: "prefix",
    matchPattern: "9.0",
  },
  {
    id: "sr-java-8",
    productId: "sp-java",
    productName: "Oracle Java SE",
    version: "8u202",
    vendor: "Oracle",
    releaseDate: "2019-01-15",
    supportEndDate: "2025-12-31",
    // Demo Scenario: EOSL Expired
    eoslDate: "2025-12-31",
    status: "EOSL",
    versionMatchRule: "exact",
    matchPattern: "8u202",
  },
  {
    id: "sr-mssql-2019",
    productId: "sp-mssql",
    productName: "Microsoft SQL Server",
    version: "2019 CU18",
    vendor: "Microsoft",
    releaseDate: "2022-10-18",
    supportEndDate: "2030-01-08",
    eoslDate: "2030-01-08",
    status: "SUPPORTED",
    versionMatchRule: "prefix",
    matchPattern: "2019",
  },
  {
    id: "sr-a360-v29",
    productId: "sp-a360",
    productName: "Automation Anywhere A360",
    version: "v29.1",
    vendor: "Automation Anywhere",
    releaseDate: "2023-11-01",
    supportEndDate: "2028-06-30",
    eoslDate: "2028-06-30",
    status: "SUPPORTED",
    versionMatchRule: "prefix",
    matchPattern: "v29",
  },
];

export const assetSoftwareInstallations: AssetSoftwareInstallation[] = [
  // D90 Scenario on RPA-P-MEM-AP02
  {
    id: "inst-tomcat-mem-ap02",
    projectGroupId: "rpa",
    assetId: "rpa-p-mem-ap02",
    productId: "sp-tomcat",
    productName: "Apache Tomcat",
    detectedVersion: "9.0.73",
    matchedReleaseId: "sr-tomcat-9",
    matchedReleaseVersion: "9.0.73",
    eoslDate: "2026-11-15",
    lifecycleStatus: "D90",
    vendor: "Apache Software Foundation",
    category: "Application Server",
    installedAt: "2023-04-10",
  },
  // EOSL Expired Scenario on RPA-COMMON-AP01
  {
    id: "inst-java-com-ap01",
    projectGroupId: "rpa",
    assetId: "rpa-common-ap01",
    productId: "sp-java",
    productName: "Oracle Java SE",
    detectedVersion: "8u202",
    matchedReleaseId: "sr-java-8",
    matchedReleaseVersion: "8u202",
    eoslDate: "2025-12-31",
    lifecycleStatus: "EOSL",
    vendor: "Oracle",
    category: "Runtime / JDK",
    installedAt: "2021-08-15",
  },
  // UNMAPPED Scenario on RPA-P-FND-AP03
  {
    id: "inst-custom-fnd-ap03",
    projectGroupId: "rpa",
    assetId: "rpa-p-fnd-ap03",
    productId: "sp-custom",
    productName: "Custom RPA Engine Plugin",
    detectedVersion: "v1.2-rc4",
    matchedReleaseId: null,
    matchedReleaseVersion: null,
    eoslDate: null,
    lifecycleStatus: "UNMAPPED",
    vendor: "Internal Engineering",
    category: "Proprietary",
    installedAt: "2024-02-01",
  },
  // Supported on A360 APs
  {
    id: "inst-a360-mem-ap01",
    projectGroupId: "rpa",
    assetId: "rpa-p-mem-ap01",
    productId: "sp-a360",
    productName: "Automation Anywhere A360",
    detectedVersion: "v29.1",
    matchedReleaseId: "sr-a360-v29",
    matchedReleaseVersion: "v29.1",
    eoslDate: "2028-06-30",
    lifecycleStatus: "SUPPORTED",
    vendor: "Automation Anywhere",
    category: "RPA Platform",
  },
  {
    id: "inst-mssql-mem-db01",
    projectGroupId: "rpa",
    assetId: "rpa-p-mem-db01",
    productId: "sp-mssql",
    productName: "Microsoft SQL Server",
    detectedVersion: "2019 CU18",
    matchedReleaseId: "sr-mssql-2019",
    matchedReleaseVersion: "2019 CU18",
    eoslDate: "2030-01-08",
    lifecycleStatus: "SUPPORTED",
    vendor: "Microsoft",
    category: "Database",
  },
];

// Legacy software installations (compatibility)
export const software: SoftwareInstall[] = assetSoftwareInstallations.map((inst) => ({
  id: inst.id,
  vmId: inst.assetId,
  name: inst.productName,
  version: inst.detectedVersion,
  vendor: inst.vendor,
  category: inst.category,
  eoslDate: inst.eoslDate,
}));

// ==========================================
// 9. SOP DOCUMENTS
// ==========================================
export const sops: SopDocument[] = [
  {
    id: "sop-mssql-failover",
    projectGroupId: "rpa",
    title: "SOP-DB-01: MSSQL High-Availability Cluster Manual Failover",
    category: "Database Failover",
    owner: "DBA Team",
    url: "https://wiki.corp/sop/mssql-failover",
    relatedVmIds: [
      "rpa-p-mem-db01",
      "rpa-p-mem-db02",
      "rpa-p-fnd-db01",
      "rpa-p-fnd-db02",
      "rpa-p-com-db01",
      "rpa-p-com-db02",
    ],
    updatedAt: "2026-08-12",
    summary:
      "Procedure to manually switch the active node in MSCS during routine patching or unrecoverable disk warnings.",
    severity: "CRITICAL",
  },
  {
    id: "sop-portal-k8s-pod",
    projectGroupId: "rpa",
    title: "SOP-K8S-04: RPA Portal Kubernetes Pod Restart & Traffic Drain",
    category: "Application Operations",
    owner: "Portal DevOps",
    url: "https://wiki.corp/sop/k8s-drain",
    relatedVmIds: ["portal-fe-01", "portal-fe-02", "portal-be-01", "portal-be-02"],
    updatedAt: "2026-09-05",
    summary:
      "Graceful drain and rolling restart guide for Portal microservices during deployment updates.",
    severity: "HIGH",
  },
  {
    id: "sop-a360-ap-cache",
    projectGroupId: "rpa",
    title: "SOP-RPA-02: A360 AP Rolling Restart and Memory Cache Purge",
    category: "RPA Platform",
    owner: "Automation COE",
    url: "https://wiki.corp/sop/a360-ap-restart",
    relatedVmIds: [
      "rpa-p-mem-ap01",
      "rpa-p-mem-ap02",
      "rpa-p-mem-ap03",
      "rpa-p-fnd-ap01",
      "rpa-p-fnd-ap02",
      "rpa-p-com-ap01",
    ],
    updatedAt: "2026-09-18",
    summary:
      "Immediate troubleshooting runbook when an AP server breaches the 90% memory utilization threshold.",
    severity: "HIGH",
  },
  {
    id: "sop-fw-policy-renew",
    projectGroupId: "rpa",
    title: "SOP-SEC-09: Firewall Policy Renewal and Urgent Extension Request",
    category: "Network Security",
    owner: "Network Operations",
    url: "https://wiki.corp/sop/firewall-renew",
    relatedVmIds: ["rpa-p-com-ap01", "rpa-q-mem-ap01"],
    updatedAt: "2026-09-01",
    summary:
      "Standard process for renewing expiring firewall policies before automatic blocking occurs.",
    severity: "MEDIUM",
  },
  {
    id: "sop-dev-tcp-diag",
    projectGroupId: "rpa",
    title: "SOP-NET-03: Telegraf TCP Probe Failure Diagnostic Protocol",
    category: "Network Troubleshooting",
    owner: "Infra Ops",
    url: "https://wiki.corp/sop/tcp-diag",
    relatedVmIds: ["rpa-d-ap01", "rpa-d-db01"],
    updatedAt: "2026-07-20",
    summary:
      "Diagnostic procedure when Ping is UP but TCP port is DOWN, verifying listener services and intermediate ACLs.",
    severity: "HIGH",
  },
];

// ==========================================
// 10. RESOURCE TRENDS (24h Fleet Avg)
// ==========================================
export const resourceTrend: ResourcePoint[] = [
  { time: "00:00", cpu: 32, memory: 58, disk: 52 },
  { time: "02:00", cpu: 28, memory: 57, disk: 52 },
  { time: "04:00", cpu: 26, memory: 56, disk: 52 },
  { time: "06:00", cpu: 30, memory: 59, disk: 52 },
  { time: "08:00", cpu: 45, memory: 68, disk: 53 },
  { time: "09:00", cpu: 58, memory: 74, disk: 54 },
  { time: "10:00", cpu: 64, memory: 79, disk: 54 },
  { time: "11:00", cpu: 61, memory: 78, disk: 55 },
  { time: "12:00", cpu: 48, memory: 71, disk: 55 },
  { time: "13:00", cpu: 55, memory: 76, disk: 55 },
  { time: "14:00", cpu: 67, memory: 82, disk: 56 },
  { time: "15:00", cpu: 63, memory: 80, disk: 56 },
  { time: "16:00", cpu: 59, memory: 77, disk: 56 },
  { time: "17:00", cpu: 52, memory: 73, disk: 56 },
  { time: "18:00", cpu: 44, memory: 67, disk: 56 },
  { time: "20:00", cpu: 38, memory: 63, disk: 56 },
  { time: "22:00", cpu: 35, memory: 60, disk: 56 },
];
