import type {
  AssetSoftwareInstallation,
  ClusterEntity,
  ConnectivityObservation,
  NasAsset,
  NetworkPolicy,
  ResourcePoint,
  SoftwareInstall,
  SoftwareProduct,
  SoftwareRelease,
  SopDocument,
  VmAsset,
} from "@/domain/models";

export const vms: VmAsset[] = [
  {
    "id": "web01",
    "hostname": "RPA-WEB01",
    "ipAddress": "10.10.10.11",
    "environment": "PROD",
    "role": "Web",
    "service": "RPA Portal",
    "zone": "WEB",
    "criticality": "HIGH",
    "osName": "Windows Server",
    "osVersion": "2022",
    "cpuCores": 8,
    "memoryGb": 16,
    "diskGb": 500,
    "cpuPct": 35,
    "memoryPct": 75,
    "diskPct": 69,
    "health": "healthy",
    "owner": "RPA Platform",
    "eoslDate": "2031-10-14",
    "grafanaPath": "/d/vm-detail?var-host=RPA-WEB01",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "web02",
    "hostname": "RPA-WEB02",
    "ipAddress": "10.10.10.12",
    "environment": "PROD",
    "role": "Web",
    "service": "RPA Portal",
    "zone": "WEB",
    "criticality": "HIGH",
    "osName": "Windows Server",
    "osVersion": "2022",
    "cpuCores": 8,
    "memoryGb": 16,
    "diskGb": 500,
    "cpuPct": 45,
    "memoryPct": 82,
    "diskPct": 74,
    "health": "healthy",
    "owner": "RPA Platform",
    "eoslDate": "2031-10-14",
    "grafanaPath": "/d/vm-detail?var-host=RPA-WEB02",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "web03",
    "hostname": "RPA-WEB03",
    "ipAddress": "10.10.10.13",
    "environment": "PROD",
    "role": "Web",
    "service": "RPA Portal",
    "zone": "WEB",
    "criticality": "HIGH",
    "osName": "Windows Server",
    "osVersion": "2022",
    "cpuCores": 8,
    "memoryGb": 16,
    "diskGb": 500,
    "cpuPct": 55,
    "memoryPct": 37,
    "diskPct": 79,
    "health": "healthy",
    "owner": "RPA Platform",
    "eoslDate": "2031-10-14",
    "grafanaPath": "/d/vm-detail?var-host=RPA-WEB03",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "web04",
    "hostname": "RPA-WEB04",
    "ipAddress": "10.10.10.14",
    "environment": "STG",
    "role": "Web",
    "service": "RPA Portal",
    "zone": "WEB",
    "criticality": "HIGH",
    "osName": "Windows Server",
    "osVersion": "2022",
    "cpuCores": 8,
    "memoryGb": 16,
    "diskGb": 500,
    "cpuPct": 65,
    "memoryPct": 44,
    "diskPct": 36,
    "health": "healthy",
    "owner": "RPA Platform",
    "eoslDate": "2031-10-14",
    "grafanaPath": "/d/vm-detail?var-host=RPA-WEB04",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "app01",
    "hostname": "RPA-APP01",
    "ipAddress": "10.10.20.11",
    "environment": "PROD",
    "role": "Application",
    "service": "Control Room",
    "zone": "APP",
    "criticality": "CRITICAL",
    "osName": "Windows Server",
    "osVersion": "2019",
    "cpuCores": 8,
    "memoryGb": 32,
    "diskGb": 500,
    "cpuPct": 47,
    "memoryPct": 83,
    "diskPct": 73,
    "health": "healthy",
    "owner": "RPA Platform",
    "eoslDate": "2029-01-09",
    "grafanaPath": "/d/vm-detail?var-host=RPA-APP01",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "app02",
    "hostname": "RPA-APP02",
    "ipAddress": "10.10.20.12",
    "environment": "PROD",
    "role": "Application",
    "service": "Control Room",
    "zone": "APP",
    "criticality": "CRITICAL",
    "osName": "Windows Server",
    "osVersion": "2019",
    "cpuCores": 8,
    "memoryGb": 32,
    "diskGb": 500,
    "cpuPct": 57,
    "memoryPct": 38,
    "diskPct": 78,
    "health": "healthy",
    "owner": "RPA Platform",
    "eoslDate": "2029-01-09",
    "grafanaPath": "/d/vm-detail?var-host=RPA-APP02",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "app03",
    "hostname": "RPA-APP03",
    "ipAddress": "10.10.20.13",
    "environment": "PROD",
    "role": "Application",
    "service": "Control Room",
    "zone": "APP",
    "criticality": "CRITICAL",
    "osName": "Windows Server",
    "osVersion": "2019",
    "cpuCores": 8,
    "memoryGb": 32,
    "diskGb": 500,
    "cpuPct": 67,
    "memoryPct": 89,
    "diskPct": 35,
    "health": "warning",
    "owner": "RPA Platform",
    "eoslDate": "2029-01-09",
    "grafanaPath": "/d/vm-detail?var-host=RPA-APP03",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "app04",
    "hostname": "RPA-APP04",
    "ipAddress": "10.10.20.14",
    "environment": "PROD",
    "role": "Application",
    "service": "Control Room",
    "zone": "APP",
    "criticality": "CRITICAL",
    "osName": "Windows Server",
    "osVersion": "2019",
    "cpuCores": 8,
    "memoryGb": 32,
    "diskGb": 500,
    "cpuPct": 77,
    "memoryPct": 52,
    "diskPct": 40,
    "health": "healthy",
    "owner": "RPA Platform",
    "eoslDate": "2029-01-09",
    "grafanaPath": "/d/vm-detail?var-host=RPA-APP04",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "app05",
    "hostname": "RPA-APP05",
    "ipAddress": "10.10.20.15",
    "environment": "PROD",
    "role": "Application",
    "service": "Control Room",
    "zone": "APP",
    "criticality": "CRITICAL",
    "osName": "Windows Server",
    "osVersion": "2019",
    "cpuCores": 8,
    "memoryGb": 32,
    "diskGb": 500,
    "cpuPct": 16,
    "memoryPct": 59,
    "diskPct": 45,
    "health": "critical",
    "owner": "RPA Platform",
    "eoslDate": "2029-01-09",
    "grafanaPath": "/d/vm-detail?var-host=RPA-APP05",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "app06",
    "hostname": "RPA-APP06",
    "ipAddress": "10.10.20.16",
    "environment": "STG",
    "role": "Application",
    "service": "Control Room",
    "zone": "APP",
    "criticality": "CRITICAL",
    "osName": "Windows Server",
    "osVersion": "2019",
    "cpuCores": 8,
    "memoryGb": 32,
    "diskGb": 500,
    "cpuPct": 26,
    "memoryPct": 66,
    "diskPct": 50,
    "health": "healthy",
    "owner": "RPA Platform",
    "eoslDate": "2029-01-09",
    "grafanaPath": "/d/vm-detail?var-host=RPA-APP06",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "db01",
    "hostname": "RPA-DB01",
    "ipAddress": "10.10.30.11",
    "environment": "PROD",
    "role": "Database",
    "service": "RPA DB",
    "zone": "DB",
    "criticality": "CRITICAL",
    "osName": "Windows Server",
    "osVersion": "2019",
    "cpuCores": 8,
    "memoryGb": 32,
    "diskGb": 500,
    "cpuPct": 65,
    "memoryPct": 43,
    "diskPct": 79,
    "health": "healthy",
    "owner": "DB Team",
    "eoslDate": "2029-01-09",
    "grafanaPath": "/d/vm-detail?var-host=RPA-DB01",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "db02",
    "hostname": "RPA-DB02",
    "ipAddress": "10.10.30.12",
    "environment": "PROD",
    "role": "Database",
    "service": "RPA DB",
    "zone": "DB",
    "criticality": "CRITICAL",
    "osName": "Windows Server",
    "osVersion": "2019",
    "cpuCores": 8,
    "memoryGb": 32,
    "diskGb": 500,
    "cpuPct": 75,
    "memoryPct": 50,
    "diskPct": 36,
    "health": "healthy",
    "owner": "DB Team",
    "eoslDate": "2029-01-09",
    "grafanaPath": "/d/vm-detail?var-host=RPA-DB02",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "db03",
    "hostname": "RPA-DB03",
    "ipAddress": "10.10.30.13",
    "environment": "PROD",
    "role": "Database",
    "service": "RPA DB",
    "zone": "DB",
    "criticality": "CRITICAL",
    "osName": "Windows Server",
    "osVersion": "2016",
    "cpuCores": 8,
    "memoryGb": 32,
    "diskGb": 500,
    "cpuPct": 14,
    "memoryPct": 57,
    "diskPct": 41,
    "health": "healthy",
    "owner": "DB Team",
    "eoslDate": "2026-11-15",
    "grafanaPath": "/d/vm-detail?var-host=RPA-DB03",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "db04",
    "hostname": "RPA-DB04",
    "ipAddress": "10.10.30.14",
    "environment": "PROD",
    "role": "Database",
    "service": "RPA DB",
    "zone": "DB",
    "criticality": "CRITICAL",
    "osName": "Windows Server",
    "osVersion": "2019",
    "cpuCores": 8,
    "memoryGb": 32,
    "diskGb": 500,
    "cpuPct": 24,
    "memoryPct": 64,
    "diskPct": 91,
    "health": "warning",
    "owner": "DB Team",
    "eoslDate": "2029-01-09",
    "grafanaPath": "/d/vm-detail?var-host=RPA-DB04",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "ctrl01",
    "hostname": "RPA-CTRL01",
    "ipAddress": "10.10.40.11",
    "environment": "PROD",
    "role": "Control",
    "service": "Bot Orchestrator",
    "zone": "CONTROL",
    "criticality": "CRITICAL",
    "osName": "Windows Server",
    "osVersion": "2022",
    "cpuCores": 8,
    "memoryGb": 32,
    "diskGb": 500,
    "cpuPct": 77,
    "memoryPct": 51,
    "diskPct": 35,
    "health": "healthy",
    "owner": "RPA Platform",
    "eoslDate": "2031-10-14",
    "grafanaPath": "/d/vm-detail?var-host=RPA-CTRL01",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "ctrl02",
    "hostname": "RPA-CTRL02",
    "ipAddress": "10.10.40.12",
    "environment": "PROD",
    "role": "Control",
    "service": "Bot Orchestrator",
    "zone": "CONTROL",
    "criticality": "CRITICAL",
    "osName": "Windows Server",
    "osVersion": "2022",
    "cpuCores": 8,
    "memoryGb": 32,
    "diskGb": 500,
    "cpuPct": 16,
    "memoryPct": 58,
    "diskPct": 40,
    "health": "healthy",
    "owner": "RPA Platform",
    "eoslDate": "2031-10-14",
    "grafanaPath": "/d/vm-detail?var-host=RPA-CTRL02",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "bot01",
    "hostname": "RPA-BOT01",
    "ipAddress": "10.10.50.11",
    "environment": "PROD",
    "role": "Bot Runner",
    "service": "RPA Bot",
    "zone": "BOT",
    "criticality": "HIGH",
    "osName": "Windows Server",
    "osVersion": "2022",
    "cpuCores": 8,
    "memoryGb": 16,
    "diskGb": 500,
    "cpuPct": 12,
    "memoryPct": 55,
    "diskPct": 37,
    "health": "healthy",
    "owner": "RPA Platform",
    "eoslDate": "2031-10-14",
    "grafanaPath": "/d/vm-detail?var-host=RPA-BOT01",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "bot02",
    "hostname": "RPA-BOT02",
    "ipAddress": "10.10.50.12",
    "environment": "PROD",
    "role": "Bot Runner",
    "service": "RPA Bot",
    "zone": "BOT",
    "criticality": "HIGH",
    "osName": "Windows Server",
    "osVersion": "2022",
    "cpuCores": 8,
    "memoryGb": 16,
    "diskGb": 500,
    "cpuPct": 22,
    "memoryPct": 62,
    "diskPct": 42,
    "health": "healthy",
    "owner": "RPA Platform",
    "eoslDate": "2031-10-14",
    "grafanaPath": "/d/vm-detail?var-host=RPA-BOT02",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "bot03",
    "hostname": "RPA-BOT03",
    "ipAddress": "10.10.50.13",
    "environment": "PROD",
    "role": "Bot Runner",
    "service": "RPA Bot",
    "zone": "BOT",
    "criticality": "HIGH",
    "osName": "Windows Server",
    "osVersion": "2022",
    "cpuCores": 8,
    "memoryGb": 16,
    "diskGb": 500,
    "cpuPct": 32,
    "memoryPct": 69,
    "diskPct": 47,
    "health": "healthy",
    "owner": "RPA Platform",
    "eoslDate": "2031-10-14",
    "grafanaPath": "/d/vm-detail?var-host=RPA-BOT03",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "bot04",
    "hostname": "RPA-BOT04",
    "ipAddress": "10.10.50.14",
    "environment": "PROD",
    "role": "Bot Runner",
    "service": "RPA Bot",
    "zone": "BOT",
    "criticality": "HIGH",
    "osName": "Windows Server",
    "osVersion": "2022",
    "cpuCores": 8,
    "memoryGb": 16,
    "diskGb": 500,
    "cpuPct": 42,
    "memoryPct": 76,
    "diskPct": 52,
    "health": "healthy",
    "owner": "RPA Platform",
    "eoslDate": "2031-10-14",
    "grafanaPath": "/d/vm-detail?var-host=RPA-BOT04",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "bot05",
    "hostname": "RPA-BOT05",
    "ipAddress": "10.10.50.15",
    "environment": "PROD",
    "role": "Bot Runner",
    "service": "RPA Bot",
    "zone": "BOT",
    "criticality": "HIGH",
    "osName": "Windows Server",
    "osVersion": "2022",
    "cpuCores": 8,
    "memoryGb": 16,
    "diskGb": 500,
    "cpuPct": 52,
    "memoryPct": 83,
    "diskPct": 57,
    "health": "healthy",
    "owner": "RPA Platform",
    "eoslDate": "2031-10-14",
    "grafanaPath": "/d/vm-detail?var-host=RPA-BOT05",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "bot06",
    "hostname": "RPA-BOT06",
    "ipAddress": "10.10.50.16",
    "environment": "PROD",
    "role": "Bot Runner",
    "service": "RPA Bot",
    "zone": "BOT",
    "criticality": "HIGH",
    "osName": "Windows Server",
    "osVersion": "2022",
    "cpuCores": 8,
    "memoryGb": 16,
    "diskGb": 500,
    "cpuPct": 89,
    "memoryPct": 38,
    "diskPct": 62,
    "health": "warning",
    "owner": "RPA Platform",
    "eoslDate": "2031-10-14",
    "grafanaPath": "/d/vm-detail?var-host=RPA-BOT06",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "bot07",
    "hostname": "RPA-BOT07",
    "ipAddress": "10.10.50.17",
    "environment": "STG",
    "role": "Bot Runner",
    "service": "RPA Bot",
    "zone": "BOT",
    "criticality": "HIGH",
    "osName": "Windows Server",
    "osVersion": "2022",
    "cpuCores": 8,
    "memoryGb": 16,
    "diskGb": 500,
    "cpuPct": 72,
    "memoryPct": 45,
    "diskPct": 67,
    "health": "healthy",
    "owner": "RPA Platform",
    "eoslDate": "2031-10-14",
    "grafanaPath": "/d/vm-detail?var-host=RPA-BOT07",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "bot08",
    "hostname": "RPA-BOT08",
    "ipAddress": "10.10.50.18",
    "environment": "DEV",
    "role": "Bot Runner",
    "service": "RPA Bot",
    "zone": "BOT",
    "criticality": "HIGH",
    "osName": "Windows Server",
    "osVersion": "2012 R2",
    "cpuCores": 8,
    "memoryGb": 16,
    "diskGb": 500,
    "cpuPct": 11,
    "memoryPct": 52,
    "diskPct": 72,
    "health": "healthy",
    "owner": "RPA Platform",
    "eoslDate": "2023-10-10",
    "grafanaPath": "/d/vm-detail?var-host=RPA-BOT08",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "vdi01",
    "hostname": "RPA-VDI01",
    "ipAddress": "10.10.60.11",
    "environment": "PROD",
    "role": "VDI",
    "service": "Bot VDI",
    "zone": "VDI",
    "criticality": "HIGH",
    "osName": "Windows 11",
    "osVersion": "23H2",
    "cpuCores": 8,
    "memoryGb": 16,
    "diskGb": 500,
    "cpuPct": 36,
    "memoryPct": 71,
    "diskPct": 45,
    "health": "healthy",
    "owner": "VDI Team",
    "eoslDate": "2028-11-10",
    "grafanaPath": "/d/vm-detail?var-host=RPA-VDI01",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "vdi02",
    "hostname": "RPA-VDI02",
    "ipAddress": "10.10.60.12",
    "environment": "PROD",
    "role": "VDI",
    "service": "Bot VDI",
    "zone": "VDI",
    "criticality": "HIGH",
    "osName": "Windows 11",
    "osVersion": "23H2",
    "cpuCores": 8,
    "memoryGb": 16,
    "diskGb": 500,
    "cpuPct": 46,
    "memoryPct": 78,
    "diskPct": 50,
    "health": "healthy",
    "owner": "VDI Team",
    "eoslDate": "2028-11-10",
    "grafanaPath": "/d/vm-detail?var-host=RPA-VDI02",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "vdi03",
    "hostname": "RPA-VDI03",
    "ipAddress": "10.10.60.13",
    "environment": "STG",
    "role": "VDI",
    "service": "Bot VDI",
    "zone": "VDI",
    "criticality": "HIGH",
    "osName": "Windows 11",
    "osVersion": "23H2",
    "cpuCores": 8,
    "memoryGb": 16,
    "diskGb": 500,
    "cpuPct": 56,
    "memoryPct": 85,
    "diskPct": 55,
    "health": "healthy",
    "owner": "VDI Team",
    "eoslDate": "2028-11-10",
    "grafanaPath": "/d/vm-detail?var-host=RPA-VDI03",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "vdi04",
    "hostname": "RPA-VDI04",
    "ipAddress": "10.10.60.14",
    "environment": "DEV",
    "role": "VDI",
    "service": "Bot VDI",
    "zone": "VDI",
    "criticality": "HIGH",
    "osName": "Windows 10",
    "osVersion": "21H2",
    "cpuCores": 8,
    "memoryGb": 16,
    "diskGb": 500,
    "cpuPct": 66,
    "memoryPct": 92,
    "diskPct": 60,
    "health": "warning",
    "owner": "VDI Team",
    "eoslDate": "2027-01-12",
    "grafanaPath": "/d/vm-detail?var-host=RPA-VDI04",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "util01",
    "hostname": "RPA-UTIL01",
    "ipAddress": "10.10.70.11",
    "environment": "PROD",
    "role": "Utility",
    "service": "Shared Services",
    "zone": "SUPPORT",
    "criticality": "MEDIUM",
    "osName": "Linux",
    "osVersion": "RHEL 9",
    "cpuCores": 4,
    "memoryGb": 16,
    "diskGb": 500,
    "cpuPct": 48,
    "memoryPct": 79,
    "diskPct": 49,
    "health": "healthy",
    "owner": "Infra Team",
    "eoslDate": "2032-05-31",
    "grafanaPath": "/d/vm-detail?var-host=RPA-UTIL01",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  },
  {
    "id": "util02",
    "hostname": "RPA-UTIL02",
    "ipAddress": "10.10.70.12",
    "environment": "PROD",
    "role": "Utility",
    "service": "Shared Services",
    "zone": "SUPPORT",
    "criticality": "MEDIUM",
    "osName": "Linux",
    "osVersion": "CentOS 7.9",
    "cpuCores": 4,
    "memoryGb": 16,
    "diskGb": 500,
    "cpuPct": 58,
    "memoryPct": 86,
    "diskPct": 54,
    "health": "healthy",
    "owner": "Infra Team",
    "eoslDate": "2024-06-30",
    "grafanaPath": "/d/vm-detail?var-host=RPA-UTIL02",
    "sourceRef": "sample/vm-inventory.xlsx",
    "lastVerifiedAt": "2026-09-20T18:00:00+09:00"
  }
];

export const software: SoftwareInstall[] = [
  {
    "id": "sw1",
    "vmId": "web01",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw2",
    "vmId": "web01",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw3",
    "vmId": "web01",
    "name": "IIS",
    "version": "10",
    "vendor": "Microsoft",
    "category": "Web Server",
    "eoslDate": "2031-10-14",
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw4",
    "vmId": "web02",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw5",
    "vmId": "web02",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw6",
    "vmId": "web02",
    "name": "IIS",
    "version": "10",
    "vendor": "Microsoft",
    "category": "Web Server",
    "eoslDate": "2031-10-14",
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw7",
    "vmId": "web03",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw8",
    "vmId": "web03",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw9",
    "vmId": "web03",
    "name": "IIS",
    "version": "10",
    "vendor": "Microsoft",
    "category": "Web Server",
    "eoslDate": "2031-10-14",
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw10",
    "vmId": "web04",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw11",
    "vmId": "web04",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw12",
    "vmId": "web04",
    "name": "IIS",
    "version": "10",
    "vendor": "Microsoft",
    "category": "Web Server",
    "eoslDate": "2031-10-14",
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw13",
    "vmId": "app01",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw14",
    "vmId": "app01",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw15",
    "vmId": "app01",
    "name": "Automation Anywhere Control Room",
    "version": "A360",
    "vendor": "Automation Anywhere",
    "category": "RPA",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw16",
    "vmId": "app01",
    "name": "Java",
    "version": "17.0.8",
    "vendor": "Eclipse Adoptium",
    "category": "Runtime",
    "eoslDate": "2029-10-31",
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw17",
    "vmId": "app02",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw18",
    "vmId": "app02",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw19",
    "vmId": "app02",
    "name": "Automation Anywhere Control Room",
    "version": "A360",
    "vendor": "Automation Anywhere",
    "category": "RPA",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw20",
    "vmId": "app02",
    "name": "Java",
    "version": "17.0.8",
    "vendor": "Eclipse Adoptium",
    "category": "Runtime",
    "eoslDate": "2029-10-31",
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw21",
    "vmId": "app03",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw22",
    "vmId": "app03",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw23",
    "vmId": "app03",
    "name": "Automation Anywhere Control Room",
    "version": "A360",
    "vendor": "Automation Anywhere",
    "category": "RPA",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw24",
    "vmId": "app03",
    "name": "Java",
    "version": "17.0.8",
    "vendor": "Eclipse Adoptium",
    "category": "Runtime",
    "eoslDate": "2026-10-31",
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw25",
    "vmId": "app04",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw26",
    "vmId": "app04",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw27",
    "vmId": "app04",
    "name": "Automation Anywhere Control Room",
    "version": "A360",
    "vendor": "Automation Anywhere",
    "category": "RPA",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw28",
    "vmId": "app04",
    "name": "Java",
    "version": "17.0.8",
    "vendor": "Eclipse Adoptium",
    "category": "Runtime",
    "eoslDate": "2029-10-31",
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw29",
    "vmId": "app05",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw30",
    "vmId": "app05",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw31",
    "vmId": "app05",
    "name": "Automation Anywhere Control Room",
    "version": "A360",
    "vendor": "Automation Anywhere",
    "category": "RPA",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw32",
    "vmId": "app05",
    "name": "Java",
    "version": "17.0.8",
    "vendor": "Eclipse Adoptium",
    "category": "Runtime",
    "eoslDate": "2029-10-31",
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw33",
    "vmId": "app06",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw34",
    "vmId": "app06",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw35",
    "vmId": "app06",
    "name": "Automation Anywhere Control Room",
    "version": "A360",
    "vendor": "Automation Anywhere",
    "category": "RPA",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw36",
    "vmId": "app06",
    "name": "Java",
    "version": "17.0.8",
    "vendor": "Eclipse Adoptium",
    "category": "Runtime",
    "eoslDate": "2029-10-31",
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw37",
    "vmId": "db01",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw38",
    "vmId": "db01",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw39",
    "vmId": "db01",
    "name": "Microsoft SQL Server",
    "version": "2019",
    "vendor": "Microsoft",
    "category": "Database",
    "eoslDate": "2030-01-08",
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw40",
    "vmId": "db02",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw41",
    "vmId": "db02",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw42",
    "vmId": "db02",
    "name": "Microsoft SQL Server",
    "version": "2019",
    "vendor": "Microsoft",
    "category": "Database",
    "eoslDate": "2030-01-08",
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw43",
    "vmId": "db03",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw44",
    "vmId": "db03",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw45",
    "vmId": "db03",
    "name": "Microsoft SQL Server",
    "version": "2019",
    "vendor": "Microsoft",
    "category": "Database",
    "eoslDate": "2030-01-08",
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw46",
    "vmId": "db04",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw47",
    "vmId": "db04",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw48",
    "vmId": "db04",
    "name": "Microsoft SQL Server",
    "version": "2019",
    "vendor": "Microsoft",
    "category": "Database",
    "eoslDate": "2030-01-08",
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw49",
    "vmId": "ctrl01",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw50",
    "vmId": "ctrl01",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw51",
    "vmId": "ctrl01",
    "name": "Automation Anywhere Bot Insight",
    "version": "A360",
    "vendor": "Automation Anywhere",
    "category": "RPA",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw52",
    "vmId": "ctrl02",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw53",
    "vmId": "ctrl02",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw54",
    "vmId": "ctrl02",
    "name": "Automation Anywhere Bot Insight",
    "version": "A360",
    "vendor": "Automation Anywhere",
    "category": "RPA",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw55",
    "vmId": "bot01",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw56",
    "vmId": "bot01",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw57",
    "vmId": "bot02",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw58",
    "vmId": "bot02",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw59",
    "vmId": "bot03",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw60",
    "vmId": "bot03",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw61",
    "vmId": "bot04",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw62",
    "vmId": "bot04",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw63",
    "vmId": "bot05",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw64",
    "vmId": "bot05",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw65",
    "vmId": "bot06",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw66",
    "vmId": "bot06",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw67",
    "vmId": "bot07",
    "name": "CrowdStrike Sensor",
    "version": "7.15",
    "vendor": "CrowdStrike",
    "category": "Security",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw68",
    "vmId": "bot07",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw69",
    "vmId": "bot08",
    "name": "Oracle Java JRE",
    "version": "8u202",
    "vendor": "Oracle",
    "category": "Runtime",
    "eoslDate": "2023-03-31",
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw70",
    "vmId": "bot08",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw71",
    "vmId": "vdi01",
    "name": "Automation Anywhere Bot Agent",
    "version": "A360",
    "vendor": "Automation Anywhere",
    "category": "RPA",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw72",
    "vmId": "vdi01",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw73",
    "vmId": "vdi02",
    "name": "Automation Anywhere Bot Agent",
    "version": "A360",
    "vendor": "Automation Anywhere",
    "category": "RPA",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw74",
    "vmId": "vdi02",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw75",
    "vmId": "vdi03",
    "name": "Automation Anywhere Bot Agent",
    "version": "A360",
    "vendor": "Automation Anywhere",
    "category": "RPA",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw76",
    "vmId": "vdi03",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw77",
    "vmId": "vdi04",
    "name": "Automation Anywhere Bot Agent",
    "version": "A360 v21",
    "vendor": "Automation Anywhere",
    "category": "RPA",
    "eoslDate": "2027-01-20",
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw78",
    "vmId": "vdi04",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw79",
    "vmId": "util01",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": null,
    "sourceRef": "sample/software-inventory.xlsx"
  },
  {
    "id": "sw80",
    "vmId": "util02",
    "name": "Telegraf",
    "version": "1.36",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "eoslDate": "2024-06-30",
    "sourceRef": "sample/software-inventory.xlsx"
  }
];

export const policies: NetworkPolicy[] = [
  {
    "id": "p1",
    "sourceVmId": "web01",
    "sourceName": "RPA-WEB01",
    "sourceIp": "10.10.10.11",
    "targetVmId": "app01",
    "targetName": "RPA-APP01",
    "targetIp": "10.10.20.11",
    "protocol": "TCP",
    "port": 8080,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2027-03-01",
    "requestId": "FW-2026-0001",
    "purpose": "Portal API",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p2",
    "sourceVmId": "web02",
    "sourceName": "RPA-WEB02",
    "sourceIp": "10.10.10.12",
    "targetVmId": "app01",
    "targetName": "RPA-APP01",
    "targetIp": "10.10.20.11",
    "protocol": "TCP",
    "port": 8080,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2027-03-01",
    "requestId": "FW-2026-0002",
    "purpose": "Portal API",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p3",
    "sourceVmId": "web03",
    "sourceName": "RPA-WEB03",
    "sourceIp": "10.10.10.13",
    "targetVmId": "app02",
    "targetName": "RPA-APP02",
    "targetIp": "10.10.20.12",
    "protocol": "TCP",
    "port": 8080,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2027-03-01",
    "requestId": "FW-2026-0003",
    "purpose": "Portal API",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p4",
    "sourceVmId": "web04",
    "sourceName": "RPA-WEB04",
    "sourceIp": "10.10.10.14",
    "targetVmId": "app02",
    "targetName": "RPA-APP02",
    "targetIp": "10.10.20.12",
    "protocol": "TCP",
    "port": 8080,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2027-03-01",
    "requestId": "FW-2026-0004",
    "purpose": "Portal API",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p5",
    "sourceVmId": "app01",
    "sourceName": "RPA-APP01",
    "sourceIp": "10.10.20.11",
    "targetVmId": "db01",
    "targetName": "RPA-DB01",
    "targetIp": "10.10.30.11",
    "protocol": "TCP",
    "port": 1433,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2027-01-31",
    "requestId": "FW-2026-0005",
    "purpose": "Control Room DB",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p6",
    "sourceVmId": "app02",
    "sourceName": "RPA-APP02",
    "sourceIp": "10.10.20.12",
    "targetVmId": "db01",
    "targetName": "RPA-DB01",
    "targetIp": "10.10.30.11",
    "protocol": "TCP",
    "port": 1433,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2027-01-31",
    "requestId": "FW-2026-0006",
    "purpose": "Control Room DB",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p7",
    "sourceVmId": "app03",
    "sourceName": "RPA-APP03",
    "sourceIp": "10.10.20.13",
    "targetVmId": "db01",
    "targetName": "RPA-DB01",
    "targetIp": "10.10.30.11",
    "protocol": "TCP",
    "port": 1433,
    "direction": "BIDIRECTIONAL",
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2026-10-02",
    "requestId": "FW-2026-0007",
    "purpose": "Control Room DB",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p8",
    "sourceVmId": "app04",
    "sourceName": "RPA-APP04",
    "sourceIp": "10.10.20.14",
    "targetVmId": "db01",
    "targetName": "RPA-DB01",
    "targetIp": "10.10.30.11",
    "protocol": "TCP",
    "port": 1433,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2027-01-31",
    "requestId": "FW-2026-0008",
    "purpose": "Control Room DB",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p9",
    "sourceVmId": "app05",
    "sourceName": "RPA-APP05",
    "sourceIp": "10.10.20.15",
    "targetVmId": "db01",
    "targetName": "RPA-DB01",
    "targetIp": "10.10.30.11",
    "protocol": "TCP",
    "port": 1433,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2027-01-31",
    "requestId": "FW-2026-0009",
    "purpose": "Control Room DB",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p10",
    "sourceVmId": "app06",
    "sourceName": "RPA-APP06",
    "sourceIp": "10.10.20.16",
    "targetVmId": "db01",
    "targetName": "RPA-DB01",
    "targetIp": "10.10.30.11",
    "protocol": "TCP",
    "port": 1433,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2027-01-31",
    "requestId": "FW-2026-0010",
    "purpose": "Control Room DB",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p11",
    "sourceVmId": "db01",
    "sourceName": "RPA-DB01",
    "sourceIp": "10.10.30.11",
    "targetVmId": "db02",
    "targetName": "RPA-DB02",
    "targetIp": "10.10.30.12",
    "protocol": "TCP",
    "port": 5022,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2026-09-18",
    "requestId": "FW-2026-0011",
    "purpose": "DB mirroring",
    "owner": "DB Team",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p12",
    "sourceVmId": "db03",
    "sourceName": "RPA-DB03",
    "sourceIp": "10.10.30.13",
    "targetVmId": "db04",
    "targetName": "RPA-DB04",
    "targetIp": "10.10.30.14",
    "protocol": "TCP",
    "port": 5022,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2027-02-28",
    "requestId": "FW-2026-0012",
    "purpose": "Reporting DB mirroring",
    "owner": "DB Team",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p13",
    "sourceVmId": "app03",
    "sourceName": "RPA-APP03",
    "sourceIp": "10.10.20.13",
    "targetVmId": null,
    "targetName": "LDAP01",
    "targetIp": "10.20.40.10",
    "protocol": "TCP",
    "port": 636,
    "direction": "BIDIRECTIONAL",
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2027-06-01",
    "requestId": "FW-2026-0013",
    "purpose": "LDAPS",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p14",
    "sourceVmId": "app02",
    "sourceName": "RPA-APP02",
    "sourceIp": "10.10.20.12",
    "targetVmId": null,
    "targetName": "SMTP01",
    "targetIp": "10.20.50.25",
    "protocol": "TCP",
    "port": 25,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2026-09-29",
    "requestId": "FW-2026-0014",
    "purpose": "SMTP relay",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p15",
    "sourceVmId": "app04",
    "sourceName": "RPA-APP04",
    "sourceIp": "10.10.20.14",
    "targetVmId": null,
    "targetName": "ERP API",
    "targetIp": "172.20.10.40",
    "protocol": "TCP",
    "port": 443,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2026-09-10",
    "requestId": "FW-2026-0015",
    "purpose": "ERP API",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p16",
    "sourceVmId": "ctrl01",
    "sourceName": "RPA-CTRL01",
    "sourceIp": "10.10.40.11",
    "targetVmId": "bot01",
    "targetName": "RPA-BOT01",
    "targetIp": "10.10.50.11",
    "protocol": "TCP",
    "port": 443,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2027-04-01",
    "requestId": "FW-2026-0016",
    "purpose": "Bot orchestration",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p17",
    "sourceVmId": "ctrl01",
    "sourceName": "RPA-CTRL01",
    "sourceIp": "10.10.40.11",
    "targetVmId": "bot02",
    "targetName": "RPA-BOT02",
    "targetIp": "10.10.50.12",
    "protocol": "TCP",
    "port": 443,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2027-04-01",
    "requestId": "FW-2026-0017",
    "purpose": "Bot orchestration",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p18",
    "sourceVmId": "ctrl01",
    "sourceName": "RPA-CTRL01",
    "sourceIp": "10.10.40.11",
    "targetVmId": "bot03",
    "targetName": "RPA-BOT03",
    "targetIp": "10.10.50.13",
    "protocol": "TCP",
    "port": 443,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2027-04-01",
    "requestId": "FW-2026-0018",
    "purpose": "Bot orchestration",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p19",
    "sourceVmId": "ctrl01",
    "sourceName": "RPA-CTRL01",
    "sourceIp": "10.10.40.11",
    "targetVmId": "bot04",
    "targetName": "RPA-BOT04",
    "targetIp": "10.10.50.14",
    "protocol": "TCP",
    "port": 443,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2027-04-01",
    "requestId": "FW-2026-0019",
    "purpose": "Bot orchestration",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p20",
    "sourceVmId": "ctrl02",
    "sourceName": "RPA-CTRL02",
    "sourceIp": "10.10.40.12",
    "targetVmId": "bot05",
    "targetName": "RPA-BOT05",
    "targetIp": "10.10.50.15",
    "protocol": "TCP",
    "port": 443,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2027-04-01",
    "requestId": "FW-2026-0020",
    "purpose": "Bot orchestration",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p21",
    "sourceVmId": "ctrl02",
    "sourceName": "RPA-CTRL02",
    "sourceIp": "10.10.40.12",
    "targetVmId": "bot06",
    "targetName": "RPA-BOT06",
    "targetIp": "10.10.50.16",
    "protocol": "TCP",
    "port": 443,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2027-04-01",
    "requestId": "FW-2026-0021",
    "purpose": "Bot orchestration",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p22",
    "sourceVmId": "ctrl02",
    "sourceName": "RPA-CTRL02",
    "sourceIp": "10.10.40.12",
    "targetVmId": "bot07",
    "targetName": "RPA-BOT07",
    "targetIp": "10.10.50.17",
    "protocol": "TCP",
    "port": 443,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2027-04-01",
    "requestId": "FW-2026-0022",
    "purpose": "Bot orchestration",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p23",
    "sourceVmId": "ctrl02",
    "sourceName": "RPA-CTRL02",
    "sourceIp": "10.10.40.12",
    "targetVmId": "bot08",
    "targetName": "RPA-BOT08",
    "targetIp": "10.10.50.18",
    "protocol": "TCP",
    "port": 443,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2027-04-01",
    "requestId": "FW-2026-0023",
    "purpose": "Bot orchestration",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p24",
    "sourceVmId": "bot01",
    "sourceName": "RPA-BOT01",
    "sourceIp": "10.10.50.11",
    "targetVmId": "vdi01",
    "targetName": "RPA-VDI01",
    "targetIp": "10.10.60.11",
    "protocol": "TCP",
    "port": 3389,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2026-11-30",
    "requestId": "FW-2026-0024",
    "purpose": "VDI session control",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p25",
    "sourceVmId": "bot02",
    "sourceName": "RPA-BOT02",
    "sourceIp": "10.10.50.12",
    "targetVmId": "vdi02",
    "targetName": "RPA-VDI02",
    "targetIp": "10.10.60.12",
    "protocol": "TCP",
    "port": 3389,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2026-11-30",
    "requestId": "FW-2026-0025",
    "purpose": "VDI session control",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p26",
    "sourceVmId": "bot03",
    "sourceName": "RPA-BOT03",
    "sourceIp": "10.10.50.13",
    "targetVmId": "vdi03",
    "targetName": "RPA-VDI03",
    "targetIp": "10.10.60.13",
    "protocol": "TCP",
    "port": 3389,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2026-11-30",
    "requestId": "FW-2026-0026",
    "purpose": "VDI session control",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p27",
    "sourceVmId": "bot04",
    "sourceName": "RPA-BOT04",
    "sourceIp": "10.10.50.14",
    "targetVmId": "vdi04",
    "targetName": "RPA-VDI04",
    "targetIp": "10.10.60.14",
    "protocol": "TCP",
    "port": 3389,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2026-11-30",
    "requestId": "FW-2026-0027",
    "purpose": "VDI session control",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p28",
    "sourceVmId": "bot01",
    "sourceName": "RPA-BOT01",
    "sourceIp": "10.10.50.11",
    "targetVmId": null,
    "targetName": "ERP API",
    "targetIp": "172.20.10.40",
    "protocol": "TCP",
    "port": 443,
    "approvalStatus": "PENDING",
    "requestedAt": "2026-01-10",
    "approvedAt": null,
    "validFrom": null,
    "expiresAt": "2027-02-01",
    "requestId": "FW-2026-0028",
    "purpose": "ERP automation",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  },
  {
    "id": "p29",
    "sourceVmId": "util01",
    "sourceName": "RPA-UTIL01",
    "sourceIp": "10.10.70.11",
    "targetVmId": null,
    "targetName": "Influx Relay",
    "targetIp": "10.20.80.20",
    "protocol": "TCP",
    "port": 443,
    "approvalStatus": "APPROVED",
    "requestedAt": "2026-01-10",
    "approvedAt": "2026-01-12",
    "validFrom": "2026-01-12",
    "expiresAt": "2026-09-20",
    "requestId": "FW-2026-0029",
    "purpose": "Monitoring relay",
    "owner": "RPA Platform",
    "sourceRef": "sample/firewall-requests.xlsx"
  }
];

export const observations: ConnectivityObservation[] = [
  {
    "policyId": "p1",
    "sourceVmId": "web01",
    "targetIp": "10.10.20.11",
    "port": 8080,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 1.1,
    "tcpLatencyMs": 2.0,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p2",
    "sourceVmId": "web02",
    "targetIp": "10.10.20.11",
    "port": 8080,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 1.5,
    "tcpLatencyMs": 2.6,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p3",
    "sourceVmId": "web03",
    "targetIp": "10.10.20.12",
    "port": 8080,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 1.9,
    "tcpLatencyMs": 3.2,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p4",
    "sourceVmId": "web04",
    "targetIp": "10.10.20.12",
    "port": 8080,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 2.3,
    "tcpLatencyMs": 3.8,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p5",
    "sourceVmId": "app01",
    "targetIp": "10.10.30.11",
    "port": 1433,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 2.7,
    "tcpLatencyMs": 4.4,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p6",
    "sourceVmId": "app02",
    "targetIp": "10.10.30.11",
    "port": 1433,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 3.1,
    "tcpLatencyMs": 5.0,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p7",
    "sourceVmId": "app03",
    "targetIp": "10.10.30.11",
    "port": 1433,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 0.7,
    "tcpLatencyMs": 5.6,
    "reversePing": "UP",
    "reverseTcp": "UP",
    "reversePingLatencyMs": 0.9,
    "reverseTcpLatencyMs": 3.1,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p8",
    "sourceVmId": "app04",
    "targetIp": "10.10.30.11",
    "port": 1433,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 1.1,
    "tcpLatencyMs": 6.2,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p9",
    "sourceVmId": "app05",
    "targetIp": "10.10.30.11",
    "port": 1433,
    "ping": "DOWN",
    "tcp": "DOWN",
    "pingLatencyMs": null,
    "tcpLatencyMs": null,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p10",
    "sourceVmId": "app06",
    "targetIp": "10.10.30.11",
    "port": 1433,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 1.9,
    "tcpLatencyMs": 2.0,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p11",
    "sourceVmId": "db01",
    "targetIp": "10.10.30.12",
    "port": 5022,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 2.3,
    "tcpLatencyMs": 2.6,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p12",
    "sourceVmId": "db03",
    "targetIp": "10.10.30.14",
    "port": 5022,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 2.7,
    "tcpLatencyMs": 3.2,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p13",
    "sourceVmId": "app03",
    "targetIp": "10.20.40.10",
    "port": 636,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 1.2,
    "tcpLatencyMs": 4.5,
    "reversePing": "UP",
    "reverseTcp": "DOWN",
    "reversePingLatencyMs": 1.4,
    "reverseTcpLatencyMs": null,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p14",
    "sourceVmId": "app02",
    "targetIp": "10.20.50.25",
    "port": 25,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 0.7,
    "tcpLatencyMs": 4.4,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p15",
    "sourceVmId": "app04",
    "targetIp": "172.20.10.40",
    "port": 443,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 1.1,
    "tcpLatencyMs": 5.0,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p16",
    "sourceVmId": "ctrl01",
    "targetIp": "10.10.50.11",
    "port": 443,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 1.5,
    "tcpLatencyMs": 5.6,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p17",
    "sourceVmId": "ctrl01",
    "targetIp": "10.10.50.12",
    "port": 443,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 1.9,
    "tcpLatencyMs": 6.2,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p18",
    "sourceVmId": "ctrl01",
    "targetIp": "10.10.50.13",
    "port": 443,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 2.3,
    "tcpLatencyMs": 1.4,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p19",
    "sourceVmId": "ctrl01",
    "targetIp": "10.10.50.14",
    "port": 443,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 2.7,
    "tcpLatencyMs": 2.0,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p20",
    "sourceVmId": "ctrl02",
    "targetIp": "10.10.50.15",
    "port": 443,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 3.1,
    "tcpLatencyMs": 2.6,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p21",
    "sourceVmId": "ctrl02",
    "targetIp": "10.10.50.16",
    "port": 443,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 0.7,
    "tcpLatencyMs": 3.2,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p22",
    "sourceVmId": "ctrl02",
    "targetIp": "10.10.50.17",
    "port": 443,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 1.1,
    "tcpLatencyMs": 3.8,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p23",
    "sourceVmId": "ctrl02",
    "targetIp": "10.10.50.18",
    "port": 443,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 1.5,
    "tcpLatencyMs": 4.4,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p24",
    "sourceVmId": "bot01",
    "targetIp": "10.10.60.11",
    "port": 3389,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 1.9,
    "tcpLatencyMs": 5.0,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p25",
    "sourceVmId": "bot02",
    "targetIp": "10.10.60.12",
    "port": 3389,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 2.3,
    "tcpLatencyMs": 5.6,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p26",
    "sourceVmId": "bot03",
    "targetIp": "10.10.60.13",
    "port": 3389,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 2.7,
    "tcpLatencyMs": 6.2,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p27",
    "sourceVmId": "bot04",
    "targetIp": "10.10.60.14",
    "port": 3389,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 3.1,
    "tcpLatencyMs": 1.4,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p28",
    "sourceVmId": "bot01",
    "targetIp": "172.20.10.40",
    "port": 443,
    "ping": "UP",
    "tcp": "UP",
    "pingLatencyMs": 0.7,
    "tcpLatencyMs": 2.0,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  },
  {
    "policyId": "p29",
    "sourceVmId": "util01",
    "targetIp": "10.20.80.20",
    "port": 443,
    "ping": "UP",
    "tcp": "DOWN",
    "pingLatencyMs": 2.8,
    "tcpLatencyMs": null,
    "checkedAt": "2026-09-21T00:27:00+09:00"
  }
];

export const sops: SopDocument[] = [
  {
    "id": "sop01",
    "title": "Control Room 접속 장애 대응",
    "category": "Application",
    "owner": "RPA Platform",
    "url": "https://confluence.example.internal/sop/control-room",
    "relatedVmIds": [
      "app01",
      "app02",
      "app03",
      "app04",
      "app05",
      "app06"
    ],
    "updatedAt": "2026-08-14"
  },
  {
    "id": "sop02",
    "title": "DB Connection / Failover 대응",
    "category": "Database",
    "owner": "DB Team",
    "url": "https://confluence.example.internal/sop/db-failover",
    "relatedVmIds": [
      "db01",
      "db02",
      "db03",
      "db04"
    ],
    "updatedAt": "2026-07-21"
  },
  {
    "id": "sop03",
    "title": "방화벽 만료 / 통신 장애 확인",
    "category": "Network",
    "owner": "RPA Platform",
    "url": "https://confluence.example.internal/sop/network",
    "relatedVmIds": [
      "app01",
      "app02",
      "app03",
      "app04",
      "app05",
      "app06"
    ],
    "updatedAt": "2026-09-02"
  },
  {
    "id": "sop04",
    "title": "Bot Runner 장애 대응",
    "category": "Bot",
    "owner": "RPA Platform",
    "url": "https://confluence.example.internal/sop/bot-runner",
    "relatedVmIds": [
      "bot01",
      "bot02",
      "bot03",
      "bot04",
      "bot05",
      "bot06",
      "bot07",
      "bot08"
    ],
    "updatedAt": "2026-08-29"
  },
  {
    "id": "sop05",
    "title": "VDI 접속 장애 대응",
    "category": "VDI",
    "owner": "VDI Team",
    "url": "https://confluence.example.internal/sop/vdi",
    "relatedVmIds": [
      "vdi01",
      "vdi02",
      "vdi03",
      "vdi04"
    ],
    "updatedAt": "2026-06-18"
  }
];

export const resourceTrend: ResourcePoint[] = [
  {
    "time": "01:00",
    "cpu": 28,
    "memory": 54,
    "disk": 61
  },
  {
    "time": "02:00",
    "cpu": 35,
    "memory": 57,
    "disk": 63
  },
  {
    "time": "03:00",
    "cpu": 42,
    "memory": 60,
    "disk": 65
  },
  {
    "time": "04:00",
    "cpu": 32,
    "memory": 63,
    "disk": 62
  },
  {
    "time": "05:00",
    "cpu": 39,
    "memory": 66,
    "disk": 64
  },
  {
    "time": "06:00",
    "cpu": 29,
    "memory": 56,
    "disk": 61
  },
  {
    "time": "07:00",
    "cpu": 36,
    "memory": 59,
    "disk": 63
  },
  {
    "time": "08:00",
    "cpu": 43,
    "memory": 62,
    "disk": 65
  },
  {
    "time": "09:00",
    "cpu": 33,
    "memory": 65,
    "disk": 62
  },
  {
    "time": "10:00",
    "cpu": 40,
    "memory": 55,
    "disk": 64
  },
  {
    "time": "11:00",
    "cpu": 30,
    "memory": 58,
    "disk": 61
  },
  {
    "time": "12:00",
    "cpu": 37,
    "memory": 61,
    "disk": 63
  },
  {
    "time": "13:00",
    "cpu": 44,
    "memory": 64,
    "disk": 65
  },
  {
    "time": "14:00",
    "cpu": 34,
    "memory": 54,
    "disk": 62
  },
  {
    "time": "15:00",
    "cpu": 41,
    "memory": 57,
    "disk": 64
  },
  {
    "time": "16:00",
    "cpu": 31,
    "memory": 60,
    "disk": 61
  },
  {
    "time": "17:00",
    "cpu": 38,
    "memory": 63,
    "disk": 63
  },
  {
    "time": "18:00",
    "cpu": 28,
    "memory": 66,
    "disk": 65
  },
  {
    "time": "19:00",
    "cpu": 35,
    "memory": 56,
    "disk": 62
  },
  {
    "time": "20:00",
    "cpu": 42,
    "memory": 59,
    "disk": 64
  },
  {
    "time": "21:00",
    "cpu": 32,
    "memory": 62,
    "disk": 61
  },
  {
    "time": "22:00",
    "cpu": 39,
    "memory": 65,
    "disk": 63
  },
  {
    "time": "23:00",
    "cpu": 29,
    "memory": 55,
    "disk": 65
  },
  {
    "time": "00:00",
    "cpu": 36,
    "memory": 58,
    "disk": 62
  }
];

export const nasAssets: NasAsset[] = [
  {
    "id": "nas01",
    "assetType": "NAS",
    "hostname": "RPA-NAS01",
    "ipAddress": "10.10.80.11",
    "environment": "PROD",
    "role": "Shared Storage",
    "service": "RPA File Store",
    "zone": "SUPPORT",
    "criticality": "HIGH",
    "health": "healthy",
    "vendor": "NetApp",
    "model": "AFF A250",
    "capacityTb": 48,
    "usedCapacityTb": 29.4,
    "protocol": "MULTI",
    "mountPath": "/mnt/rpa-share",
    "status": "ONLINE",
    "owner": "Storage Team",
    "targetVms": ["app01", "app02", "bot01", "bot02", "ctrl01"]
  },
  {
    "id": "nas02",
    "assetType": "NAS",
    "hostname": "RPA-NAS02",
    "ipAddress": "10.10.80.12",
    "environment": "STG",
    "role": "Backup Storage",
    "service": "RPA Backup Store",
    "zone": "SUPPORT",
    "criticality": "MEDIUM",
    "health": "healthy",
    "vendor": "Synology",
    "model": "FS3600",
    "capacityTb": 24,
    "usedCapacityTb": 14.8,
    "protocol": "NFS",
    "mountPath": "/mnt/rpa-backup",
    "status": "ONLINE",
    "owner": "Storage Team",
    "targetVms": ["app06", "bot07"]
  }
];

export const clusters: ClusterEntity[] = [
  {
    "id": "cluster-sql01",
    "name": "MSSQL-PRD",
    "type": "MSCS",
    "vip": "10.10.30.100",
    "environment": "PROD",
    "zone": "DB",
    "status": "HEALTHY",
    "owner": "DB Team",
    "members": [
      {
        "clusterId": "cluster-sql01",
        "assetId": "db01",
        "hostname": "RPA-DB01",
        "ipAddress": "10.10.30.11",
        "role": "ACTIVE",
        "priority": 1,
        "status": "ONLINE"
      },
      {
        "clusterId": "cluster-sql01",
        "assetId": "db02",
        "hostname": "RPA-DB02",
        "ipAddress": "10.10.30.12",
        "role": "PASSIVE",
        "priority": 2,
        "status": "STANDBY"
      }
    ],
    "services": [
      {
        "clusterId": "cluster-sql01",
        "serviceType": "MSSQL",
        "instanceName": "MSSQLSERVER",
        "port": 1433,
        "version": "2019 CU22"
      }
    ]
  }
];

export const softwareProducts: SoftwareProduct[] = [
  {
    "id": "prod-sql",
    "name": "Microsoft SQL Server",
    "vendor": "Microsoft",
    "category": "Database",
    "description": "Enterprise Relational Database Management System"
  },
  {
    "id": "prod-java",
    "name": "Java OpenJDK / JRE",
    "vendor": "Eclipse Adoptium",
    "category": "Runtime",
    "description": "Java SE Platform Runtime Environment"
  },
  {
    "id": "prod-win",
    "name": "Windows Server",
    "vendor": "Microsoft",
    "category": "Operating System",
    "description": "Enterprise Server Operating System"
  },
  {
    "id": "prod-aa",
    "name": "Automation Anywhere",
    "vendor": "Automation Anywhere",
    "category": "RPA Platform",
    "description": "Enterprise RPA Bot Agent & Control Room"
  },
  {
    "id": "prod-telegraf",
    "name": "Telegraf Agent",
    "vendor": "InfluxData",
    "category": "Monitoring",
    "description": "Server-side metrics collector & probe agent"
  },
  {
    "id": "prod-cs",
    "name": "CrowdStrike Falcon Sensor",
    "vendor": "CrowdStrike",
    "category": "Security",
    "description": "Endpoint Protection & EDR sensor"
  }
];

export const softwareReleases: SoftwareRelease[] = [
  {
    "id": "rel-java8",
    "productId": "prod-java",
    "productName": "Java OpenJDK / JRE",
    "version": "8.0",
    "vendor": "Oracle",
    "releaseDate": "2014-03-18",
    "supportEndDate": "2023-03-31",
    "eoslDate": "2023-03-31",
    "status": "EOSL",
    "versionMatchRule": "prefix",
    "matchPattern": "8"
  },
  {
    "id": "rel-java17",
    "productId": "prod-java",
    "productName": "Java OpenJDK / JRE",
    "version": "17.0",
    "vendor": "Eclipse Adoptium",
    "releaseDate": "2021-09-14",
    "supportEndDate": "2029-10-31",
    "eoslDate": "2029-10-31",
    "status": "SUPPORTED",
    "versionMatchRule": "prefix",
    "matchPattern": "17"
  },
  {
    "id": "rel-win2012r2",
    "productId": "prod-win",
    "productName": "Windows Server",
    "version": "2012 R2",
    "vendor": "Microsoft",
    "releaseDate": "2013-10-18",
    "supportEndDate": "2023-10-10",
    "eoslDate": "2023-10-10",
    "status": "EOSL",
    "versionMatchRule": "exact",
    "matchPattern": "2012 R2"
  },
  {
    "id": "rel-win2016",
    "productId": "prod-win",
    "productName": "Windows Server",
    "version": "2016",
    "vendor": "Microsoft",
    "releaseDate": "2016-10-12",
    "supportEndDate": "2026-11-15",
    "eoslDate": "2026-11-15",
    "status": "D90",
    "versionMatchRule": "exact",
    "matchPattern": "2016"
  },
  {
    "id": "rel-win2019",
    "productId": "prod-win",
    "productName": "Windows Server",
    "version": "2019",
    "vendor": "Microsoft",
    "releaseDate": "2018-10-02",
    "supportEndDate": "2029-01-09",
    "eoslDate": "2029-01-09",
    "status": "SUPPORTED",
    "versionMatchRule": "exact",
    "matchPattern": "2019"
  },
  {
    "id": "rel-win2022",
    "productId": "prod-win",
    "productName": "Windows Server",
    "version": "2022",
    "vendor": "Microsoft",
    "releaseDate": "2021-08-18",
    "supportEndDate": "2031-10-14",
    "eoslDate": "2031-10-14",
    "status": "SUPPORTED",
    "versionMatchRule": "exact",
    "matchPattern": "2022"
  },
  {
    "id": "rel-aa21",
    "productId": "prod-aa",
    "productName": "Automation Anywhere",
    "version": "A360 v21",
    "vendor": "Automation Anywhere",
    "releaseDate": "2021-06-01",
    "supportEndDate": "2027-01-20",
    "eoslDate": "2027-01-20",
    "status": "D180",
    "versionMatchRule": "prefix",
    "matchPattern": "A360 v21"
  },
  {
    "id": "rel-aa26",
    "productId": "prod-aa",
    "productName": "Automation Anywhere",
    "version": "A360 v26",
    "vendor": "Automation Anywhere",
    "releaseDate": "2023-08-01",
    "supportEndDate": "2029-06-30",
    "eoslDate": "2029-06-30",
    "status": "SUPPORTED",
    "versionMatchRule": "prefix",
    "matchPattern": "A360"
  },
  {
    "id": "rel-telegraf1",
    "productId": "prod-telegraf",
    "productName": "Telegraf Agent",
    "version": "1.36",
    "vendor": "InfluxData",
    "releaseDate": "2024-02-15",
    "supportEndDate": "2028-12-31",
    "eoslDate": "2028-12-31",
    "status": "SUPPORTED",
    "versionMatchRule": "prefix",
    "matchPattern": "1.36"
  }
];

export const assetSoftwareInstallations: AssetSoftwareInstallation[] = [
  {
    "id": "inst01",
    "assetId": "app01",
    "productId": "prod-win",
    "productName": "Windows Server",
    "detectedVersion": "2019",
    "matchedReleaseId": "rel-win2019",
    "matchedReleaseVersion": "2019",
    "eoslDate": "2029-01-09",
    "lifecycleStatus": "SUPPORTED",
    "vendor": "Microsoft",
    "category": "Operating System"
  },
  {
    "id": "inst02",
    "assetId": "app01",
    "productId": "prod-aa",
    "productName": "Automation Anywhere",
    "detectedVersion": "A360 v26",
    "matchedReleaseId": "rel-aa26",
    "matchedReleaseVersion": "A360 v26",
    "eoslDate": "2029-06-30",
    "lifecycleStatus": "SUPPORTED",
    "vendor": "Automation Anywhere",
    "category": "RPA"
  },
  {
    "id": "inst03",
    "assetId": "app01",
    "productId": "prod-java",
    "productName": "Java OpenJDK / JRE",
    "detectedVersion": "17.0.8",
    "matchedReleaseId": "rel-java17",
    "matchedReleaseVersion": "17.0",
    "eoslDate": "2029-10-31",
    "lifecycleStatus": "SUPPORTED",
    "vendor": "Eclipse Adoptium",
    "category": "Runtime"
  },
  {
    "id": "inst04",
    "assetId": "app01",
    "productId": "prod-telegraf",
    "productName": "Telegraf Agent",
    "detectedVersion": "1.36",
    "matchedReleaseId": "rel-telegraf1",
    "matchedReleaseVersion": "1.36",
    "eoslDate": "2028-12-31",
    "lifecycleStatus": "SUPPORTED",
    "vendor": "InfluxData",
    "category": "Monitoring"
  },
  {
    "id": "inst05",
    "assetId": "app01",
    "productId": "prod-cs",
    "productName": "CrowdStrike Falcon Sensor",
    "detectedVersion": "7.15",
    "matchedReleaseId": null,
    "matchedReleaseVersion": null,
    "eoslDate": null,
    "lifecycleStatus": "UNMAPPED",
    "vendor": "CrowdStrike",
    "category": "Security"
  },
  {
    "id": "inst06",
    "assetId": "db03",
    "productId": "prod-win",
    "productName": "Windows Server",
    "detectedVersion": "2016",
    "matchedReleaseId": "rel-win2016",
    "matchedReleaseVersion": "2016",
    "eoslDate": "2026-11-15",
    "lifecycleStatus": "D90",
    "vendor": "Microsoft",
    "category": "Operating System"
  },
  {
    "id": "inst07",
    "assetId": "bot08",
    "productId": "prod-win",
    "productName": "Windows Server",
    "detectedVersion": "2012 R2",
    "matchedReleaseId": "rel-win2012r2",
    "matchedReleaseVersion": "2012 R2",
    "eoslDate": "2023-10-10",
    "lifecycleStatus": "EOSL",
    "vendor": "Microsoft",
    "category": "Operating System"
  },
  {
    "id": "inst08",
    "assetId": "bot08",
    "productId": "prod-java",
    "productName": "Java OpenJDK / JRE",
    "detectedVersion": "8.0.202",
    "matchedReleaseId": "rel-java8",
    "matchedReleaseVersion": "8.0",
    "eoslDate": "2023-03-31",
    "lifecycleStatus": "EOSL",
    "vendor": "Oracle",
    "category": "Runtime"
  },
  {
    "id": "inst09",
    "assetId": "vdi04",
    "productId": "prod-aa",
    "productName": "Automation Anywhere",
    "detectedVersion": "A360 v21",
    "matchedReleaseId": "rel-aa21",
    "matchedReleaseVersion": "A360 v21",
    "eoslDate": "2027-01-20",
    "lifecycleStatus": "D180",
    "vendor": "Automation Anywhere",
    "category": "RPA"
  }
];


